const $=s=>document.querySelector(s);const categoryView=$('#category-view'),categoryDetail=$('#category-detail'),categoryBanner=$('#category-banner'),grid=$('#grid'),searchInput=$('#menu-search'),menuSection=$('#menu'),homeSection=$('#home'),reservationSection=$('#reservation'),aboutSection=$('#about'),productPage=$('#product-page'),relatedGrid=$('#related-grid');
const API='/api/products',CATEGORY_API='/api/categories';
const categoryImages={Breakfast:'https://images.unsplash.com/photo-1570882716056-9b4919acaf51?auto=format&fit=crop&w=1800&q=85',Manakish:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1800&q=85','Cold Appetizers':'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=1800&q=85','Hot Appetizers':'https://images.unsplash.com/photo-1623653387945-2fd25214f8fc?auto=format&fit=crop&w=1800&q=85',Salads:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1800&q=85',Soups:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1800&q=85',Sandwich:'https://images.unsplash.com/photo-1521305916504-4a1121188589?auto=format&fit=crop&w=1800&q=85',Pizza:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1800&q=85',Pasta:'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1800&q=85','Main Course':'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1800&q=85','Mixed Grill':'https://images.unsplash.com/photo-1633857471930-bfa8d0be5e4a?auto=format&fit=crop&w=1800&q=85','Mixed Taste':'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1800&q=85',Desserts:'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1800&q=85','Cheese Cake':'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=1800&q=85','Arabisk Ice Cream':'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?auto=format&fit=crop&w=1800&q=85','Cocktail & Refreshing Drinks':'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1800&q=85','Energy Drinks':'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1800&q=85',Juices:'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=1800&q=85',Mojitos:'https://images.unsplash.com/photo-1568926825354-c277ddca9bec?auto=format&fit=crop&w=1800&q=85','Milk Shakes':'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=1800&q=85',Tea:'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1800&q=85',Coffee:'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1800&q=85',Latte:'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1800&q=85','Soft Drinks':'https://images.unsplash.com/photo-1543253687-c4b3b9c1aa8d?auto=format&fit=crop&w=1800&q=85','Drinking Water':'https://images.unsplash.com/photo-1560023907-5f339617ea30?auto=format&fit=crop&w=1800&q=85',Sheesha:'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1800&q=85'};
const translations={ar:{watch:'شاهد طريقة التحضير',available:'متوفر',unavailable:'غير متوفر',view:'التفاصيل ←',relatedEyebrow:'YOU MAY ALSO LIKE',relatedTitle:'أصناف قد تعجبك',relatedLead:'استكشف خيارات أخرى من نفس القسم.'},en:{watch:'Watch Preparation',available:'Available',unavailable:'Unavailable',view:'View details →',relatedEyebrow:'YOU MAY ALSO LIKE',relatedTitle:'You May Also Like',relatedLead:'Explore more options from the same category.'}};
let language=localStorage.getItem('ARABISK_LANG')||'ar',categories=[],currentCategory=null,currentItems=[],currentProduct=null;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const slug=v=>String(v??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const cslug=c=>slug(c.id),pslug=p=>slug(p.nameEn||p.nameAr);
const routeInfo=()=>{const path=location.pathname.replace(/\/$/,'')||'/';if(path==='/menu')return{page:'menu'};if(path==='/reservation')return{page:'reservation'};const m=path.match(/^\/menu\/([^/]+)(?:\/([^/]+))?$/);return m?{page:'category',category:decodeURIComponent(m[1]),product:m[2]?decodeURIComponent(m[2]):null}:{page:'home'};};
async function load(url){const r=await fetch(url);if(!r.ok)throw new Error('request failed');return r.json()}
function productVisual(p,c){return p.imageUrl||categoryImages[c.id]||c.imageUrl||''}
function renderCategories(){const en=language==='en';categoryView.innerHTML=categories.filter(c=>c.active!==false).map(c=>`<a class="category-card" href="/menu/${cslug(c)}"><div class="category-image"><img src="${esc(categoryImages[c.id]||c.imageUrl||'')}" alt="${esc(en?c.nameEn:c.nameAr)}" loading="lazy"></div><span class="category-shade"></span><div class="category-copy"><span class="cat-en">${esc(c.nameEn)}</span><h3>${esc(en?c.nameEn:c.nameAr)}</h3><span class="category-arrow">${en?'Explore →':'اكتشف القسم ←'}</span></div></a>`).join('')}
function renderItems(items){const en=language==='en',q=searchInput.value.trim().toLowerCase();const filtered=q?items.filter(i=>`${i.nameAr} ${i.nameEn}`.toLowerCase().includes(q)):items;grid.innerHTML=filtered.map(i=>{const real=Boolean(i.imageKey||i.imageUrl);const visual=productVisual(i,currentCategory);return `<a class="item item-link${real?' has-product-image':''}" href="/menu/${cslug(currentCategory)}/${pslug(i)}"><div>${visual?`<div class="item-thumb" style="background-image:url('${esc(visual)}')"></div>`:''}<span class="cat">${esc(i.nameEn)}</span><h3>${esc(en?i.nameEn:i.nameAr)}</h3><p>${esc(en?(i.descriptionEn||'A signature ARABISK selection.'):(i.descriptionAr||'اختيار من قائمة ARABISK المميزة'))}</p></div><div class="item-bottom"><div class="price">AED ${Number(i.price).toFixed(0)}</div><span class="item-open">${translations[language].view}</span></div></a>`}).join('')||`<p class="empty-menu">${en?'No items are available in this category yet.':'لا توجد أصناف في هذا القسم حالياً.'}</p>`}
function renderRelated(items,p){const en=language==='en';const list=items.filter(x=>x.id!==p.id).slice(0,3);relatedGrid.innerHTML=list.map(i=>`<a class="related-card${i.imageKey||i.imageUrl?' has-product-image':''}" href="/menu/${cslug(currentCategory)}/${pslug(i)}"><div class="related-thumb" style="background-image:url('${esc(productVisual(i,currentCategory))}')"><span>${esc(i.nameEn)}</span></div><div class="related-body"><h3>${esc(en?i.nameEn:i.nameAr)}</h3><strong>AED ${Number(i.price).toFixed(0)}</strong></div></a>`).join('')||`<p class="empty-menu">${en?'No related items yet.':'لا توجد أصناف مقترحة حاليًا.'}</p>`}
function renderCategory(c,items){currentCategory=c;currentProduct=null;const en=language==='en';$('#detail-title').textContent=en?c.nameEn:c.nameAr;$('#detail-eyebrow').textContent=c.nameEn.toUpperCase();$('#detail-lead').textContent=en?`Explore our ${c.nameEn} selection.`:`استكشف تشكيلة ${c.nameAr}.`;categoryBanner.style.backgroundImage=`url(\"${esc(categoryImages[c.id]||c.imageUrl||'')}\")`;renderItems(items)}
function renderProduct(p,c){currentProduct=p;const en=language==='en',visual=productVisual(p,c),real=Boolean(p.imageKey||p.imageUrl);$('#product-title').textContent=en?p.nameEn:p.nameAr;$('#product-subtitle').textContent=en?p.nameEn:p.nameAr;$('#product-name-en').textContent=p.nameEn;$('#product-category-label').textContent=c.nameEn.toUpperCase();$('#product-lead').textContent=en?`A signature selection from our ${c.nameEn} menu.`:`اختيار مميز من قسم ${c.nameAr}.`;$('#product-description').textContent=en?(p.descriptionEn||'A signature ARABISK selection.'):(p.descriptionAr||'اختيار مميز من قائمة ARABISK.');$('#product-price').textContent=`AED ${Number(p.price).toFixed(0)}`;$('#product-availability').textContent=p.available?translations[language].available:translations[language].unavailable;const visualEl=$('#product-visual');visualEl.style.backgroundImage=`url(\"${esc(visual)}\")`;visualEl.classList.toggle('has-real-image',real);visualEl.setAttribute('aria-label',en?p.nameEn:p.nameAr);const b=$('#product-video-btn');if(p.videoUrl){b.hidden=false;b.onclick=()=>openVideo(p.videoUrl,en?p.nameEn:p.nameAr)}else b.hidden=true;relatedGrid.innerHTML='<div class="menu-loading"></div><div class="menu-loading"></div><div class="menu-loading"></div>';load(`${API}?category=${encodeURIComponent(c.id)}`).then(items=>renderRelated(items,p)).catch(()=>{relatedGrid.innerHTML=''}) ;document.title=`${en?p.nameEn:p.nameAr} — ARABISK`}
function applyLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';$('#lang-toggle').textContent=language==='ar'?'EN':'ع';renderCategories();if(currentProduct)renderProduct(currentProduct,currentCategory);else if(currentCategory)renderCategory(currentCategory,currentItems)}
function setMode(m){const home=m==='home',menu=m==='menu',cat=m==='category',prod=m==='product',reservation=m==='reservation';homeSection.hidden=!home;menuSection.hidden=!(menu||cat);reservationSection.hidden=!reservation;aboutSection.hidden=!home;productPage.hidden=!prod;categoryView.hidden=!menu;categoryDetail.hidden=!cat;$('#menu-heading').hidden=!menu;document.body.classList.toggle('category-route',menu||cat||prod);document.body.classList.toggle('reservation-route',reservation)}
async function openMenu(){setMode('menu');renderCategories();scrollTo(0,0)}
async function openReservation(){setMode('reservation');scrollTo(0,0)}
async function openCategory(c){setMode('category');searchInput.value='';grid.innerHTML='<div class="menu-loading"></div>';try{currentItems=await load(`${API}?category=${encodeURIComponent(c.id)}`);renderCategory(c,currentItems)}catch(e){console.error(e);grid.innerHTML='<p class="empty-menu">تعذر تحميل القسم حاليًا.</p>'}scrollTo(0,0)}
function openProduct(c,p){setMode('product');renderProduct(p,c);scrollTo(0,0)}
function goHome(){location.assign('/')}
async function initRoute(){const r=routeInfo();if(r.page==='home'){setMode('home');return}if(r.page==='menu'){await openMenu();return}if(r.page==='reservation'){await openReservation();return}const c=categories.find(x=>cslug(x)===r.category);if(!c)return goHome();if(!r.product)return openCategory(c);try{const items=await load(`${API}?category=${encodeURIComponent(c.id)}`),p=items.find(x=>pslug(x)===r.product);if(p)openProduct(c,p);else goHome()}catch(e){console.error(e);goHome()}}
$('#back-to-categories').addEventListener('click',goHome);$('#back-to-category').addEventListener('click',()=>currentCategory?location.assign(`/menu/${cslug(currentCategory)}`):goHome());searchInput.addEventListener('input',()=>renderItems(currentItems));$('#lang-toggle').addEventListener('click',()=>{language=language==='ar'?'en':'ar';localStorage.setItem('ARABISK_LANG',language);applyLanguage()});
const videoModal=$('#video-modal'),productVideo=$('#product-video'),videoTitle=$('#video-title'),videoFallback=$('#video-fallback');function openVideo(url,title){videoTitle.textContent=title;productVideo.src=url;productVideo.hidden=false;videoFallback.hidden=true;videoModal.classList.add('show');videoModal.setAttribute('aria-hidden','false');productVideo.play().catch(()=>{})}function closeVideo(){productVideo.pause();productVideo.removeAttribute('src');productVideo.load();videoModal.classList.remove('show');videoModal.setAttribute('aria-hidden','true')}$('#video-close').addEventListener('click',closeVideo);videoModal.addEventListener('click',e=>{if(e.target===videoModal)closeVideo()});productVideo.addEventListener('error',()=>{productVideo.hidden=true;videoFallback.hidden=false});
const reservationForm=$('#reservation-form'),reservationMessage=$('#reservation-message'),reservationDate=$('#reservation-date');const localToday=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);reservationDate.min=localToday;reservationForm.addEventListener('submit',async e=>{e.preventDefault();reservationMessage.textContent='';const submit=reservationForm.querySelector('button[type="submit"]');submit.disabled=true;try{const r=await fetch('/api/reservations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#reservation-name').value,phone:$('#reservation-phone').value,date:reservationDate.value,time:$('#reservation-time').value,guests:Number($('#reservation-guests').value),notes:$('#reservation-notes').value})});if(!r.ok)throw new Error();reservationMessage.textContent=language==='ar'?'تم استلام طلب الحجز بنجاح. سنتواصل معك لتأكيد الموعد.':'Your reservation request was received. We will contact you to confirm.';reservationForm.reset();reservationDate.min=localToday}catch(e){console.error(e);reservationMessage.textContent=language==='ar'?'تعذر إرسال طلب الحجز حاليًا. حاول مرة أخرى.':'Unable to submit the reservation right now.'}finally{submit.disabled=false}});
(async()=>{try{categories=await load(CATEGORY_API);applyLanguage();await initRoute()}catch(e){console.error(e);categoryView.innerHTML='<p class="empty-menu">تعذر تحميل الأقسام حاليًا.</p>'}})();