const CART_KEY='arabisk-cart-v1';
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const readCart=()=>{try{const value=JSON.parse(localStorage.getItem(CART_KEY)||'[]');return Array.isArray(value)?value.filter(x=>x&&x.id&&Number(x.price)>=0&&Number(x.qty)>0):[]}catch{return[]}};
const saveCart=(items)=>localStorage.setItem(CART_KEY,JSON.stringify(items));
let cart=readCart();
const total=()=>cart.reduce((sum,x)=>sum+Number(x.price)*Number(x.qty),0);
const count=()=>cart.reduce((sum,x)=>sum+Number(x.qty),0);
function add(item){const found=cart.find(x=>x.id===item.id);if(found)found.qty+=1;else cart.push({id:String(item.id),nameAr:String(item.nameAr||item.nameEn||''),price:Number(item.price)||0,imageUrl:String(item.imageUrl||''),qty:1});saveCart(cart);render();openCart();}
function setQty(id,qty){const item=cart.find(x=>x.id===id);if(!item)return;if(qty<=0)cart=cart.filter(x=>x.id!==id);else item.qty=qty;saveCart(cart);render();}
function clear(){cart=[];saveCart(cart);render();}
function render(){const badge=document.querySelector('#arabisk-cart-count');if(badge){badge.textContent=count();badge.hidden=count()===0}const lines=document.querySelector('#arabisk-cart-lines');if(!lines)return;lines.innerHTML=cart.length?cart.map(x=>`<div class="ac-line"><div class="ac-line-main">${x.imageUrl?`<img src="${esc(x.imageUrl)}" alt="" loading="lazy">`:''}<div><strong>${esc(x.nameAr)}</strong><small>AED ${Number(x.price).toFixed(0)}</small></div></div><div class="ac-qty"><button data-cart-dec="${esc(x.id)}" type="button">−</button><span>${Number(x.qty)}</span><button data-cart-inc="${esc(x.id)}" type="button">+</button></div></div>`).join(''):'<p class="ac-empty">السلة فارغة حاليًا.</p>';const sum=document.querySelector('#arabisk-cart-total');if(sum)sum.textContent=`AED ${total().toFixed(0)}`;const checkout=document.querySelector('#arabisk-checkout');if(checkout)checkout.hidden=!cart.length;}
function openCart(){document.querySelector('#arabisk-cart')?.classList.add('show');}
function closeCart(){document.querySelector('#arabisk-cart')?.classList.remove('show');}
function inject(){if(document.querySelector('#arabisk-cart'))return;document.body.insertAdjacentHTML('beforeend',`<button id="arabisk-cart-open" class="ac-fab" type="button" aria-label="فتح السلة"><span>🛒</span><b id="arabisk-cart-count" hidden>0</b></button><div id="arabisk-cart" class="ac-overlay"><aside class="ac-panel" role="dialog" aria-modal="true" aria-labelledby="ac-title"><button id="arabisk-cart-close" class="ac-close" type="button">×</button><div class="ac-head"><span>ARABISK ORDER</span><h2 id="ac-title">سلة طلبك</h2><p>راجع الأصناف ثم أرسل الطلب للمطعم.</p></div><div id="arabisk-cart-lines" class="ac-lines"></div><div class="ac-total"><span>الإجمالي</span><strong id="arabisk-cart-total">AED 0</strong></div><form id="arabisk-checkout" class="ac-form" hidden><label>الاسم<input id="ac-name" maxlength="80" required></label><label>رقم الهاتف<input id="ac-phone" maxlength="40" inputmode="tel" required></label><label>طريقة الطلب<select id="ac-type"><option value="dine_in">داخل المطعم</option><option value="pickup">استلام من المطعم</option></select></label><label>ملاحظات<textarea id="ac-notes" maxlength="300" rows="3" placeholder="أي ملاحظات على الطلب…"></textarea></label><button class="ac-submit" type="submit">إرسال الطلب</button><p id="ac-status" class="ac-status"></p></form></aside></div>`);document.querySelector('#arabisk-cart-open').onclick=openCart;document.querySelector('#arabisk-cart-close').onclick=closeCart;document.querySelector('#arabisk-cart').addEventListener('click',e=>{if(e.target.id==='arabisk-cart')closeCart();const dec=e.target.dataset.cartDec,inc=e.target.dataset.cartInc;if(dec){const item=cart.find(x=>x.id===dec);if(item)setQty(dec,item.qty-1)}if(inc){const item=cart.find(x=>x.id===inc);if(item)setQty(inc,item.qty+1)}});document.querySelector('#arabisk-checkout').addEventListener('submit',submitOrder);render();}
async function submitOrder(event){event.preventDefault();if(!cart.length)return;const form=event.currentTarget,button=form.querySelector('.ac-submit'),status=document.querySelector('#ac-status');button.disabled=true;status.textContent='جاري إرسال الطلب…';try{const payload={name:document.querySelector('#ac-name').value.trim(),phone:document.querySelector('#ac-phone').value.trim(),orderType:document.querySelector('#ac-type').value,notes:document.querySelector('#ac-notes').value.trim(),items:cart.map(x=>({productId:x.id,quantity:Number(x.qty)}))};const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'تعذر إرسال الطلب.');status.textContent=`تم استلام طلبك رقم ${data.id}. الإجمالي AED ${Number(data.total).toFixed(0)}.`;form.reset();clear();setTimeout(closeCart,1800)}catch(error){status.textContent=error.message}finally{button.disabled=false}}
window.ARABISK_CART={add,open:openCart,close:closeCart,render};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();