import crypto from 'node:crypto';

const CATEGORY_STATE_KEY='data/arabisk-categories.json';
const MAX_CATEGORY_IMAGE_BYTES=15*1024*1024;
const CATEGORY_IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp','image/avif']);
const cleanText=(v,max=180)=>String(v??'').trim().slice(0,max);
const cleanKey=(v)=>String(v??'').trim().replace(/^\/+/, '').slice(0,500);
const cleanUrl=(v)=>String(v??'').trim().slice(0,1000);
const publicCategory=(c,storageReady,presign)=>({...c,imageUrl:c.imageKey&&storageReady?presign('GET',c.imageKey,900):(c.imageUrl||'')});

export function registerCategoryRoutes(app,{categories,products,storageReady,presign,readJson,writeJson,deleteObject,requireAdminApiKey}){
  const restoreCategories=async()=>{if(!storageReady)return;const saved=await readJson(CATEGORY_STATE_KEY,null);if(Array.isArray(saved)&&saved.length)categories.splice(0,categories.length,...saved);};
  const persist=()=>void writeJson(CATEGORY_STATE_KEY,categories);
  const nextId=()=>{const max=categories.reduce((n,c)=>{const m=String(c.id||'').match(/^C(\d+)$/);return Math.max(n,m?Number(m[1]):0);},0);return `C${String(max+1).padStart(3,'0')}`;};

  app.get('/api/categories',(_req,res)=>res.json(categories.map(c=>publicCategory(c,storageReady,presign))));
  app.post('/api/categories',requireAdminApiKey,(req,res)=>{const b=req.body||{};const nameAr=cleanText(b.nameAr,100),nameEn=cleanText(b.nameEn,120);if(!nameAr||!nameEn)return res.status(400).json({message:'nameAr and nameEn are required'});if(categories.some(c=>c.nameAr===nameAr||c.nameEn.toLowerCase()===nameEn.toLowerCase()))return res.status(409).json({message:'Category with the same name already exists'});const c={id:nextId(),nameAr,nameEn,imageUrl:cleanUrl(b.imageUrl),imageKey:cleanKey(b.imageKey),sortOrder:categories.length+1,active:b.active!==undefined?Boolean(b.active):true};categories.push(c);persist();return res.status(201).json(publicCategory(c,storageReady,presign));});
  app.patch('/api/categories/:id',requireAdminApiKey,(req,res)=>{const c=categories.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({message:'Category not found'});const b=req.body||{};const oldImageKey=c.imageKey||'';if(b.nameAr!==undefined){c.nameAr=cleanText(b.nameAr,100);if(!c.nameAr)return res.status(400).json({message:'Arabic category name cannot be empty'});}if(b.nameEn!==undefined){c.nameEn=cleanText(b.nameEn,120);if(!c.nameEn)return res.status(400).json({message:'English category name cannot be empty'});}if(b.active!==undefined)c.active=Boolean(b.active);if(b.sortOrder!==undefined&&Number.isFinite(Number(b.sortOrder)))c.sortOrder=Math.max(1,Number(b.sortOrder));if(b.imageUrl!==undefined)c.imageUrl=cleanUrl(b.imageUrl);if(b.imageKey!==undefined)c.imageKey=cleanKey(b.imageKey);if(categories.some(x=>x.id!==c.id&&(x.nameAr===c.nameAr||x.nameEn.toLowerCase()===c.nameEn.toLowerCase())))return res.status(409).json({message:'Category with the same name already exists'});if(storageReady&&b.imageKey!==undefined&&oldImageKey&&oldImageKey!==c.imageKey)void deleteObject(oldImageKey);persist();return res.json(publicCategory(c,storageReady,presign));});
  app.delete('/api/categories/:id',requireAdminApiKey,(req,res)=>{const i=categories.findIndex(c=>c.id===req.params.id);if(i<0)return res.status(404).json({message:'Category not found'});const c=categories[i];const linked=products.filter(p=>p.categoryId===c.id).length;if(linked)return res.status(409).json({message:`لا يمكن حذف القسم لأنه يحتوي على ${linked} صنف. انقل الأصناف إلى قسم آخر أولاً.`});categories.splice(i,1);if(storageReady&&c.imageKey)void deleteObject(c.imageKey);categories.forEach((x,n)=>x.sortOrder=n+1);persist();return res.json({ok:true,removed:c});});
  app.post('/api/categories/images/presign',requireAdminApiKey,(req,res)=>{if(!storageReady)return res.status(503).json({message:'Image storage is not configured on the web service.'});const categoryId=cleanText(req.body?.categoryId,40),fileName=cleanText(req.body?.fileName,160).replace(/[^a-zA-Z0-9._-]/g,'-'),contentType=cleanText(req.body?.contentType,80).toLowerCase(),size=Number(req.body?.size);if(categoryId&&!categories.some(c=>c.id===categoryId))return res.status(404).json({message:'Category not found'});if(!fileName||!CATEGORY_IMAGE_TYPES.has(contentType))return res.status(400).json({message:'Only JPG, PNG, WebP and AVIF images are supported.'});if(!Number.isFinite(size)||size<1||size>MAX_CATEGORY_IMAGE_BYTES)return res.status(400).json({message:'Maximum category image size is 15 MB.'});const targetId=categoryId||`new-${crypto.randomUUID()}`;const key=`categories/${targetId}/${crypto.randomUUID()}-${fileName}`;try{return res.json({key,uploadUrl:presign('PUT',key,900),expiresIn:900});}catch(error){console.error(error);return res.status(503).json({message:'Unable to prepare category image upload.'});}});
  app.post('/api/categories/images/delete-presign',requireAdminApiKey,(req,res)=>{if(!storageReady)return res.status(503).json({message:'Image storage is not configured on the web service.'});const c=categories.find(x=>x.id===cleanText(req.body?.categoryId,40));if(!c)return res.status(404).json({message:'Category not found'});if(!c.imageKey)return res.json({url:'',key:''});try{return res.json({url:presign('DELETE',c.imageKey,900),key:c.imageKey});}catch(error){console.error(error);return res.status(503).json({message:'Unable to prepare category image deletion.'});}});
  return restoreCategories;
}
