import crypto from 'node:crypto';

const MAX_IMAGE_BYTES = 15 * 1024 * 1024;
const MAX_VIDEO_BYTES = 120 * 1024 * 1024;
const IMAGE_TYPES = new Set(['image/jpeg','image/png','image/webp','image/avif']);
const VIDEO_TYPES = new Set(['video/mp4','video/webm','video/quicktime']);
const clean = (value, max = 500) => String(value ?? '').trim().slice(0, max);
const cleanKey = (value) => clean(value, 500).replace(/^\/+/, '');
const safeType = (value) => clean(value, 80).toLowerCase();
const makeId = () => `M${crypto.randomUUID().replace(/-/g,'').slice(0,16)}`;

export function registerMemoriesRoutes(app, { storageReady, presign, readJson, writeJson, deleteObject, requireAdminApiKey }) {
  const STATE_KEY = 'data/arabisk-memories.json';
  const state = { memories: [] };
  let persistQueue = Promise.resolve();
  const persist = () => { const snapshot=structuredClone(state); persistQueue=persistQueue.catch(()=>{}).then(()=>writeJson(STATE_KEY,snapshot)); return persistQueue; };
  const restore = async () => { if(!storageReady)return; const saved=await readJson(STATE_KEY,null); if(saved&&Array.isArray(saved.memories))state.memories.splice(0,state.memories.length,...saved.memories); };
  const publicMemory = (m) => ({id:m.id,text:m.text,mediaType:m.mediaType,imageUrl:m.imageKey&&storageReady?presign('GET',m.imageKey,900):'',videoUrl:m.videoKey&&storageReady?presign('GET',m.videoKey,900):'',displayName:m.displayName||'مجهول',createdAt:m.createdAt,likes:Number(m.likes||0),comments:Array.isArray(m.comments)?m.comments.map(c=>({id:c.id,text:c.text,displayName:c.displayName||'مجهول',createdAt:c.createdAt})):[],commentsCount:Array.isArray(m.comments)?m.comments.length:0,shareCount:Number(m.shareCount||0),pinned:Boolean(m.pinned)});
  app.get('/api/memories',(req,res)=>{const sort=clean(req.query.sort,20)==='popular'?'popular':'latest';const list=state.memories.filter(m=>m.hidden!==true).map(publicMemory).sort((a,b)=>sort==='popular'?(b.likes+b.commentsCount*2+b.shareCount)-(a.likes+a.commentsCount*2+a.shareCount):String(b.createdAt).localeCompare(String(a.createdAt)));res.json(list);});
  app.post('/api/memories/upload',(req,res)=>{if(!storageReady)return res.status(503).json({message:'تخزين الوسائط غير مُعد على الخدمة.'});const type=safeType(req.body?.contentType),size=Number(req.body?.size),kind=IMAGE_TYPES.has(type)?'image':VIDEO_TYPES.has(type)?'video':'';const max=kind==='image'?MAX_IMAGE_BYTES:MAX_VIDEO_BYTES;if(!kind||!Number.isFinite(size)||size<1||size>max)return res.status(400).json({message:kind==='image'?'الصورة يجب أن تكون حتى 15MB.':'الفيديو يجب أن يكون حتى 120MB.'});const extension=clean(req.body?.fileName,80).split('.').pop()?.replace(/[^a-z0-9]/gi,'').toLowerCase()||(kind==='image'?'jpg':'mp4');const key=`memories/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${extension}`;try{res.json({kind,key,uploadUrl:presign('PUT',key,900),expiresIn:900});}catch(error){console.error('Memory upload presign failed:',error);res.status(503).json({message:'تعذر تجهيز رفع الوسائط.'});}});
  app.post('/api/memories',async(req,res)=>{const b=req.body||{},text=clean(b.text,1200),displayName=clean(b.displayName,80)||'مجهول',imageKey=cleanKey(b.imageKey),videoKey=cleanKey(b.videoKey);if(!text&&!imageKey&&!videoKey)return res.status(400).json({message:'أضف نصًا أو صورة أو فيديو.'});if(imageKey&&videoKey)return res.status(400).json({message:'يمكن نشر صورة أو فيديو واحد مع النص.'});const memory={id:makeId(),text,displayName,imageKey,videoKey,mediaType:imageKey?'image':videoKey?'video':'text',likes:0,shareCount:0,comments:[],reports:[],hidden:false,pinned:false,createdAt:new Date().toISOString()};state.memories.push(memory);await persist();res.status(201).json(publicMemory(memory));});
  app.post('/api/memories/:id/like',async(req,res)=>{const m=state.memories.find(x=>x.id===req.params.id&&x.hidden!==true);if(!m)return res.status(404).json({message:'Memory not found'});m.likes=Number(m.likes||0)+1;await persist();res.json({likes:m.likes});});
  app.post('/api/memories/:id/share',async(req,res)=>{const m=state.memories.find(x=>x.id===req.params.id&&x.hidden!==true);if(!m)return res.status(404).json({message:'Memory not found'});m.shareCount=Number(m.shareCount||0)+1;await persist();res.json({shareCount:m.shareCount});});
  app.post('/api/memories/:id/comments',async(req,res)=>{const m=state.memories.find(x=>x.id===req.params.id&&x.hidden!==true);if(!m)return res.status(404).json({message:'Memory not found'});const text=clean(req.body?.text,500),displayName=clean(req.body?.displayName,80)||'مجهول';if(!text)return res.status(400).json({message:'اكتب تعليقًا أولًا.'});m.comments.push({id:crypto.randomUUID(),text,displayName,createdAt:new Date().toISOString()});await persist();res.json({commentsCount:m.comments.length});});
  app.post('/api/memories/:id/report',async(req,res)=>{const m=state.memories.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({message:'Memory not found'});m.reports.push({id:crypto.randomUUID(),reason:clean(req.body?.reason,160)||'محتوى غير مناسب',createdAt:new Date().toISOString()});await persist();res.json({ok:true});});
  app.get('/api/admin/memories',requireAdminApiKey,(_req,res)=>res.json(state.memories.map(m=>({...publicMemory(m),hidden:Boolean(m.hidden),reportsCount:Array.isArray(m.reports)?m.reports.length:0,comments:m.comments||[],reports:m.reports||[]})).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))));
  app.patch('/api/admin/memories/:id',requireAdminApiKey,async(req,res)=>{const m=state.memories.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({message:'Memory not found'});if(req.body?.text!==undefined)m.text=clean(req.body.text,1200);if(req.body?.displayName!==undefined)m.displayName=clean(req.body.displayName,80)||'مجهول';if(req.body?.hidden!==undefined)m.hidden=Boolean(req.body.hidden);if(req.body?.pinned!==undefined)m.pinned=Boolean(req.body.pinned);if(req.body?.clearReports)m.reports=[];await persist();res.json(publicMemory(m));});
  app.delete('/api/admin/memories/:id/comments/:commentId',requireAdminApiKey,async(req,res)=>{const m=state.memories.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({message:'Memory not found'});const i=(m.comments||[]).findIndex(c=>c.id===req.params.commentId);if(i<0)return res.status(404).json({message:'Comment not found'});m.comments.splice(i,1);await persist();res.json({ok:true});});
  app.delete('/api/admin/memories/:id',requireAdminApiKey,async(req,res)=>{const i=state.memories.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({message:'Memory not found'});const [m]=state.memories.splice(i,1);if(storageReady){if(m.imageKey)void deleteObject(m.imageKey);if(m.videoKey)void deleteObject(m.videoKey);}await persist();res.json({ok:true});});
  return {restore};
}
