const defs = {
  'Breakfast': [['فطور أرابيسك','Arabisk Breakfast',94],['فطور الحارة','AL Hara Breakfast',84],['فطور الحارة مع شيشة','AL Hara Breakfast with Shisha',105],['فتة حمص','Hummus Fattah',32],['فول مدمس','Foul Mudammas',22],['لبنة','Labnah',20],['بيض مخفوق','Scrambled Eggs',22],['شكشوكة','Shakshouka',24],['صحن فول','Foul Dish',22],['صحن فلافل','Falafel Plate',22]],
  'Manakish': [['مناقيش زعتر','Zaatar Manakish',18],['مناقيش جبنة','Cheese Manakish',22],['مناقيش ديك رومي وجبن','Turkey and Cheese Manakish',24],['مناقيش لحمة أرمينية','Armenian Meat Manakish',28],['مناقيش زعتر وجبن','Cheese Zaatar Manakish',24],['مناقيش لحم مع جبن','Beef and Cheese Manakish',26],['مناقيش أرابيسك','Arabisk Manakish',36]],
  'Soups': [['شوربة عدس','Lentil Soup',18],['شوربة فطر','Mushroom Soup',22],['شوربة خضار','Vegetables Soup',20],['شوربة ذرة','Corn Soup',22],['شوربة دجاج','Chicken Soup',24],['شوربة سي فود','Sea Food Soup',34]],
  'Salads': [['سلطة لايف ستايل','Lifestyle Salad',50],['سلطة الشيف','Chef Salad',48],['سلطة سيزر','Caesar Salad',44],['تبولة','Tabboulah',34],['فتوش','Fattoush',34],['سلطة أرابيسك','Arabisk Salad',52],['سلطة جرجير','Arugula Salad',36]],
  'Cold Appetizers': [['حمص','Hummus',24],['حمص بيروتي','Hummus Beiruti',26],['ورق عنب','Vine Leaves',32],['متبل','Mutabbal',26],['كبة نية','Kibbeh Neiya',54],['بابا غنوج','Baba Ghanoug',26],['شنكليش','Shankleash',28],['مكدوس','Makdous',28],['محمرة','Muhamara',24]],
  'Hot Appetizers': [['حمص باللحمة','Hummus with Meat',38],['بطاطا حارة','Spicy Potato',28],['بطاطا مقلية','French Fries',18],['جبن حلوم مشوي','Grilled Halloumi',34],['سمبوسك لحمة','Meat Samosa',32],['نقانق فخارة','Sausage',38],['كبة مقلية','Fried Kibbeh',34],['برك بالجبنة','Cheese Burak',32],['فطائر سبانخ','Spinach Fatayar',24],['كبدة دجاج','Chicken Liver',36],['فخارة لحم','Meat Casserole',48]],
  'Sandwich': [['برجر لحم','Beef Burger',42],['برجر دجاج','Chicken Burger',38],['فرانسيسكو ساندويتش','Francisco Sandwich',38],['فاهيتا لحم','Meat Fajita',42],['فاهيتا دجاج','Chicken Fajita',38],['ساندويتش كباب','Kabab Sandwich',36],['ساندويتش شيش طاووق','Tawook Sandwich',34],['زنجر دجاج ساندويتش','Chicken Zinger Sandwich',44],['برجر زنجر ساندويتش','Burger Zinger Sandwich',40]],
  'Pizza': [['بيتزا مارغريتا','Pizza Margherita',46],['بيتزا خضار','Pizza Vegetables',48],['بيتزا دجاج باربيكيو','Pizza Chicken Barbeque',54],['بيتزا بيبروني','Pizza Pepperoni',56],['بيتزا رانش','Pizza Ranch',58],['بيتزا سي فود','Sea Food Pizza',64]],
  'Pasta': [['بيني ألفريدو','Penne Alfredo',56],['بيني أرابياتا','Penne Arabyata',48],['فيتوتشيني فنجّي','Fettuccine Funghi',58],['سباجيتي بولونيز','Spaghetti Bolognese',52],['باستا سي فود','Sea Food Pasta',64]],
  'Main Course': [['كوردون بلو','Cordon Bleu',68],['دجاج ألا كيف','Chicken Ala Kaif',68],['دجاج ألا فونجي إسكالوب','Chicken Ala Fonji Escalope',66],['دجاج إسكالوب','Chicken Escalope',52],['باستا دجاج ألا فونجي إسكالوب','Chicken Ala Fonji Escalope Pasta',68],['سلمون مشوي','Grilled Salmon',84],['شريحة لحم بالفطر','Beef Steak Mushroom',84]],
  'Mixed Grill': [['كباب بيتي','Kabab Baity',62],['مشاوي أرابيسك مشكلة (نصف كيلو)','Arabisk Mix Grill (500g)',134],['مشاوي أرابيسك مشكلة (1 كيلو)','Arabisk Mix Grill (1 kg)',226],['أجنحة دجاج مشوية','Grilled Chicken Wings',40],['مشاوي أرابيسك المشكلة','Arabisk Mixed Grill',88],['مشاوي ميكس جريل','Mix Grill',64],['مشاوي عادي كيلو','Mix Grill (1 kilo)',190],['نص مشاوي عادي','Mix Grill (1/2 kilo)',110],['ريش لحم','Lamb Chops',90],['تكا لحم ضأن','Lamb Tikka',68],['كباب','Kabab',48],['شيش طاووق','Shish Tawook',56],['نصف دجاج مشوي','Half Grilled Chicken',44],['عرايس','Arayes',46],['عرايس توشكا','Arayes Toushka',48]],
  'Mixed Taste': [['بلو جاميكا','Blue Jamaica',34],['جراند سموثي','Grand Smoothie',32],['كريزي سموثي','Crazy Smoothie',36],['مكس بيري سموثي','Mix Berry Smoothie',36],['أرابيسك سموثي','Arabisk Smoothie',38]],
  'Desserts': [['كريب نوتيلا','Nutella Crepe',40],['كنافة','Kunafa',32],['أم علي','UM Ali',34],['أوريو مادنس','Oreo Madness',32],['طبق فواكه موسمي صغير','Seasonal Small Fruit Platter',36],['طبق فواكه موسمي كبير','Seasonal Large Fruit Platter',70],['كيكة عيد ميلاد خاصة','Birthday Special Cake',52]],
  'Cheese Cake': [['تشيز كيك فراولة','Cheese Cake Strawberry',32],['تشيز كيك شوكولاتة','Cheese Cake Chocolate',32],['تشيز كيك بلوبيري','Cheese Cake Blueberry',32],['تشيز كيك سولت آند كراميل','Cheese Cake Salt and Caramel',32],['تشيز كيك فستاشيو','Cheese Cake Pistachio',32],['تشيز كيك لوتس','Cheese Cake Lotus',32]],
  'Arabisk Ice Cream': [['أوريو مادنس','Oreo Madness',32],['حلوى الموز سبلت','Banana Split',28],['آيس كريم مشكل','Ice Cream Mix',22]],
  'Cocktail & Refreshing Drinks': [['طبقات الكوكتيل','Cocktail Layers',38],['بلو ليمونادة','Blue Lemonade',36],['عصير الليمون الوردي','Pink Lemonade',36],['أرابيسك ليمونادة','Arabisk Lemonade',38]],
  'Energy Drinks': [['برافوس','Bravos',38],['أورو بلو','Oro Blue',36],['ريد بول','Red Bull',24]],
  'Juices': [['عصير برتقال','Orange Juice',26],['عصير ليمون','Lemon Juice',24],['عصير مانجا','Mango Juice',28],['عصير فراولة','Strawberry Juice',28],['عصير بطيخ أحمر','Watermelon Juice',26],['عصير ليمون ونعناع','Lemon Mint Juice',26],['عصير أفوكادو','Avocado Juice',40],['لبن عيران','Laban Ayran',28],['عصير جزر','Carrot Juice',28],['عصير تفاح','Apple Juice',28]],
  'Mojitos': [['موهيتو الكتريك','Electric Mojito',36],['موهيتو الفراولة','Mojito Strawberry',36],['موهيتو باشن فروت','Mojito Passion Fruit',36],['كلاسيك موهيتو','Classic Mojito',32],['موهيتو بلوبيري','Blueberry Mojito',36]],
  'Milk Shakes': [['لوتس شيك','Lotus Shake',38],['ميلك شيك المانجا','Mango Milk Shake',38],['ميلك شيك الموز','Banana Milk Shake',38],['ميلك شيك الشوكولاتة','Chocolate Milk Shake',38],['ميلك شيك الأوريو','Oreo Milk Shake',38],['ميلك شيك فراولة','Strawberry Milk Shake',38]],
  'Tea': [['شاي ليبتون','Lipton Tea',16],['شاي أخضر','Green Tea',16],['شاي بالنعناع','Mint Tea',16],['زعتر','Zatar',18],['ميرمية','Meramiya',18],['يانسون','Anise',18],['بابونج','Chamomile',18],['شاي بالزنجبيل والليمون','Ginger Tea with Lemon',26],['شاي مغربي حجم صغير','Moroccan Tea S',32],['شاي مغربي حجم كبير','Moroccan Tea L',38],['شاي الدراق البارد','Ice Peach Tea',32],['شاي باشن فروت بارد','Ice Passion Fruit Tea',32],['إبريق شاي','Tea Pot',28],['شاي تركي','Turkish Tea',34]],
  'Coffee': [['قهوة تركية','Turkish Coffee',20],['قهوة تركية دبل','Double Turkish Coffee',26],['إسبريسو','Espresso',22],['دبل إسبريسو','Double Espresso',26],['ميكاتو','Macchiato',26],['أمريكانو','Americano',26],['كابتشينو','Cappuccino',26],['فرابتشينو','Frappuccino',26],['شيكولاتة ساخنة','Hot Chocolate',28],['موكا','Mocha',28],['قهوة عربي','Arabic Coffee',54],['كورتادو','Cortado',26],['نسكافيه بلاك','Nescafe Black',26],['نسكافيه باللبن','Nescafe With Milk',26]],
  'Latte': [['سبانيش لاتيه','Spanish Latte',34],['لاتيه بارد','Ice Latte',30],['كوفي لاتيه','Coffee Latte',29],['فرابتشينو','Frappuccino',26]],
  'Soft Drinks': [['كولا دايت','Diet Cola',16],['كولا زيرو','Cola Zero',16],['دايت سبرايت','Diet Sprite',16],['سبرايت','Sprite',16],['فانتا','Fanta',16],['كوكاكولا','Coca Cola',16],['ماونتن ديو','Mountain Dew',16]],
  'Drinking Water': [['مياه غازية','Perrier Water',17],['مياه غازية كبيرة','Big Perrier Water',30],['مياه معدنية صغيرة','Small Mineral Water',12],['مياه معدنية كبيرة','Big Mineral Water',18]],
  'Sheesha': [['كيوي','Kiwi',65],['كيوي ونعناع','Kiwi With Mint',65],['فراولة','Strawberry',65],['فراولة ونعناع','Strawberry With Mint',65],['علكة','Gum',65],['علكة ونعناع','Gum With Mint',65],['برتقال','Orange',65],['برتقال ونعناع','Orange With Mint',65],['روز فانيليا','Rose Vanilla',65],['كرز','Cherry',65],['كرز ونعناع','Cherry With Mint',65],['علكة وقرفة','Gum Cinnamon',65],['بطيخ ونعناع','Watermelon With Mint',65],['بطيخ','Watermelon',65],['شمام','Melon',65],['خوخ','Peach',65],['تغيير راس','Extra Ras',34],['ليالي أرابيسك','Layali Arabisk',72],['أرابيسك','Arabisk',72],['تفاح ونعناع فاخر','Apple With Mint Fakher',65],['تفاحتين ونخلة','Double Apple Nakhla',65],['نعناع','Mint',65],['ليمون ونعناع','Lemon Mint',65],['تفاحتين فاخر','Double Apple Fakher',65],['تفاحتين نعناع نخلة','Apple Mint Nakhla',65],['عنب','Grape',65],['عنب ونعناع','Grape With Mint',65],['علكة مستكة','Gum Mesteka',65],['عنب وتوت','Grape Blueberry',65],['بلوبيري','Blueberry',65],['بلوبيري ونعناع','Blueberry Mint',65],['لف','Love',72],['أناناس','Pineapple',65],['ليمون','Lemon',65],['ورد','Flower',65],['باشن فروت','Passion Fruit',65]]
};
export const categoryImages = { Breakfast:'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=1000&q=85', Manakish:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1000&q=85','Cold Appetizers':'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=1000&q=85','Hot Appetizers':'https://images.unsplash.com/photo-1623653387945-2fd25214f8fc?auto=format&fit=crop&w=1000&q=85',Salads:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=85',Soups:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85',Sandwich:'https://images.unsplash.com/photo-1521305916504-4a1121188589?auto=format&fit=crop&w=1000&q=85',Pizza:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1000&q=85',Pasta:'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1000&q=85','Main Course':'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=85','Mixed Grill':'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=85','Mixed Taste':'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85',Desserts:'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1000&q=85','Cheese Cake':'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=1000&q=85','Arabisk Ice Cream':'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?auto=format&fit=crop&w=1000&q=85','Cocktail & Refreshing Drinks':'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1000&q=85','Energy Drinks':'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1000&q=85',Juices:'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=1000&q=85',Mojitos:'https://images.unsplash.com/photo-1568926825354-c277ddca9bec?auto=format&fit=crop&w=1000&q=85','Milk Shakes':'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=1000&q=85',Tea:'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1000&q=85',Coffee:'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1000&q=85',Latte:'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1000&q=85','Soft Drinks':'https://images.unsplash.com/photo-1543253687-c4b3b9c1aa8d?auto=format&fit=crop&w=1000&q=85','Drinking Water':'https://images.unsplash.com/photo-1560023907-5f339617ea30?auto=format&fit=crop&w=1000&q=85',Sheesha:'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1000&q=85' };
const arNames = {'Breakfast':'الفطور','Manakish':'المناقيش','Cold Appetizers':'المقبلات الباردة','Hot Appetizers':'المقبلات الساخنة','Salads':'السلطات','Soups':'الشوربات','Sandwich':'السندويتش','Pizza':'البيتزا','Pasta':'الباستا','Main Course':'الأطباق الرئيسية','Mixed Grill':'المشاوي المشكلة','Mixed Taste':'المذاق المشكل','Desserts':'الحلويات','Cheese Cake':'تشيز كيك','Arabisk Ice Cream':'آيس كريم أرابيسك','Cocktail & Refreshing Drinks':'الكوكتيلات والمشروبات المنعشة','Energy Drinks':'مشروبات الطاقة','Juices':'العصائر','Mojitos':'الموهيتو','Milk Shakes':'ميلك شيك','Tea':'الشاي','Coffee':'القهوة','Latte':'اللاتيه','Soft Drinks':'المشروبات الغازية','Drinking Water':'المياه','Sheesha':'الشيشة'};
export const categories = Object.keys(defs).map((id,index)=>({id,nameAr:arNames[id]||id,nameEn:id,imageUrl:categoryImages[id]||'',sortOrder:index+1,active:true}));
let seq=0;
export const products = Object.entries(defs).flatMap(([categoryId,items])=>items.map(([nameAr,nameEn,price])=>({id:`P${String(++seq).padStart(3,'0')}`,categoryId,nameAr,nameEn,descriptionAr:'',descriptionEn:'',imageUrl:'',price:Number(price),available:true,videoKey:'',sortOrder:seq})));
