(() => {
'use strict';
const $=s=>document.querySelector(s);
const currency=v=>new Intl.NumberFormat(document.documentElement.lang==='en'?'en-AE':'ar-AE',{style:'currency',currency:'AED',maximumFractionDigits:2}).format(Number(v)||0);
const state={offer:null,product:null,timer:0};
const getJson=async(url,fallback)=>{try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)return fallback;const d=await r.json();return d??fallback}catch{return fallback}};
const imageFor=p=>p?.imageUrl||'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=84';
function updateTimer(){const t=$('#offers-timer');if(!t)return;const ts=Date.parse(state.offer?.endsAt||'');if(!Number.isFinite(ts)||ts<=Date.now()){t.hidden=true;return}const m=Math.max(0,Math.floor((ts-Date.now())/60000)),d=Math.floor(m/1440),h=Math.floor((m%1440)/60),mm=m%60;t.hidden=false;t.textContent=d>0?'ينتهي خلال '+d+' يوم '+String(h).padStart(2,'0')+':'+String(mm).padStart(2,'0'):'ينتهي خلال '+String(h).padStart(2,'0')+':'+String(mm).padStart(2,'0')}
function render(){const o=state.offer,c=$('#today-offer-card'),e=$('#offers-empty'),l=$('#offers-state');if(!o?.enabled){if(c)c.hidden=true;if(e)e.hidden=false;if(l)l.hidden=true;return}const p=state.product,i=$('#offers-image');if(i){i.src=imageFor(p);i.alt=p?.nameAr||p?.nameEn||'العرض الحالي من ARABISK'}if($('#offers-badge'))$('#offers-badge').textContent=o.badge||'عرض اليوم';if($('#offers-title'))$('#offers-title').textContent=o.title||'اختيار اليوم من ARABISK';if($('#offers-message'))$('#offers-message').textContent=o.message||'اختيار مميز من القائمة متاح اليوم.';if($('#offers-product'))$('#offers-product').textContent=p?(p.nameAr||p.nameEn||'الصنف المختار'):'عرض عام من ARABISK';if($('#offers-price'))$('#offers-price').textContent=p?currency(p.price):'عرض خاص';const a=$('#offers-order');if(a){a.textContent=(o.ctaLabel||'اطلب الآن')+' ←';a.href=p?'/menu/'+encodeURIComponent(String(p.categoryId||''))+'/'+encodeURIComponent(String(p.id||'')):'/menu'}if(c)c.hidden=false;if(e)e.hidden=true;if(l)l.hidden=true;updateTimer()}
async function init(){const [o,ps]=await Promise.all([getJson('/api/promotions/today',null),getJson('/api/products',[])]);state.offer=o&&typeof o==='object'?o:null;const list=Array.isArray(ps)?ps:[];if(state.offer?.productId)state.product=list.find(p=>String(p.id)===String(state.offer.productId)&&p.available!==false)||null;render();window.clearInterval(state.timer);state.timer=window.setInterval(updateTimer,30000);window.addEventListener('arabisk:language-updated',render)}
init().catch(()=>{if($('#offers-state'))$('#offers-state').textContent='تعذر تحميل العرض حاليًا. حاول فتح الصفحة مرة أخرى.'});
})();