import express from 'express';
import cors from 'cors';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'url';
import { presign, storageReady, readJson, writeJson, deleteObject } from './storage.js';
import { categories, products } from './menu-data.js';
import { requireAdminApiKey, isAdminApiKeyValid } from './admin-auth.js';
import { registerMediaRoutes } from './media-routes.js';
import { registerCategoryRoutes } from './category-routes.js';
import { registerStudioRoutes } from './studio-routes.js';

const app = express();
const port = Number(process.env.PORT || 3000);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dist = path.join(__dirname, 'dist');
const MAX_VIDEO_BYTES = 120 * 1024 * 1024;
const VIDEO_TYPES = new Set(['video/mp4', 'video/webm', 'video/quicktime']);
const STATE_KEY = 'data/arabisk-state.json';
const MENU_VERSION = 2;
const allowedCorsOrigins = new Set(['https://arabiskadmin-production.up.railway.app','http://localhost:4174','http://127.0.0.1:4174','http://localhost:5173','http://127.0.0.1:5173']);
const corsOptions = { origin(origin, callback){ if(!origin || allowedCorsOrigins.has(origin)) return callback(null,true); return callback(null,false); }, methods:['GET','POST','PATCH','DELETE','OPTIONS'], allowedHeaders:['Content-Type','X-Arabisk-Admin-Key'] };
app.disable('x-powered-by');
app.use(cors(corsOptions));
app.options(/.*/, cors(corsOptions));
app.use((req,res,next)=>{ res.setHeader('X-Content-Type-Options','nosniff'); res.setHeader('Referrer-Policy','strict-origin-when-cross-origin'); res.setHeader('X-Frame-Options','SAMEORIGIN'); res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()'); if(req.path==='/health'||req.path.startsWith('/api/')) res.setHeader('Cache-Control','no-store'); next(); });
app.use(express.json({limit:'1mb'}));

const cleanText=(value,max=180)=>String(value??'').trim().slice(0,max);
const cleanKey=(value)=>String(value??'').trim().replace(/^\/+/, '').slice(0,500);
const cleanUrl=(value)=>String(value??'').trim().slice(0,1000);
const withMediaUrls=(product)=>({...product,imageUrl:product.imageKey&&storageReady?presign('GET',product.imageKey,900):(product.imageUrl||''),videoUrl:product.videoKey&&storageReady?presign('GET',product.videoKey,900):''});

const orders=[]; const customers=[]; const reservations=[];
const reservationRate=new Map(); const orderRate=new Map();
const RESERVATION_RATE_WINDOW_MS=10*60*1000; const RESERVATION_RATE_LIMIT=8;
const ORDER_RATE_WINDOW_MS=10*60*1000; const ORDER_RATE_LIMIT=10;
const getClientKey=(req)=>String(req.ip||req.headers['x-forwarded-for']||'unknown').split(',')[0].trim().slice(0,120)||'unknown';
const createRateLimit=(store,windowMs,limit,message)=>(req,res,next)=>{const now=Date.now(),key=getClientKey(req),previous=store.get(key);if(!previous||now-previous.startedAt>=windowMs){store.set(key,{startedAt:now,count:1});return next()}if(previous.count>=limit){const retryAfter=Math.max(1,Math.ceil((windowMs-(now-previous.startedAt))/1000));res.setHeader('Retry-After',String(retryAfter));return res.status(429).json({message,retryAfter})}previous.count+=1;return next()};
const reservationRateLimit=createRateLimit(reservationRate,RESERVATION_RATE_WINDOW_MS,RESERVATION_RATE_LIMIT,'Too many reservation requests. Please try again later.');
const orderRateLimit=createRateLimit(orderRate,ORDER_RATE_WINDOW_MS,ORDER_RATE_LIMIT,'Too many order requests. Please try again later.');
setInterval(()=>{const now=Date.now();for(const [key,entry] of reservationRate)if(now-entry.startedAt>RESERVATION_RATE_WINDOW_MS*2)reservationRate.delete(key);for(const [key,entry] of orderRate)if(now-entry.startedAt>ORDER_RATE_WINDOW_MS*2)orderRate.delete(key)},Math.min(RESERVATION_RATE_WINDOW_MS,ORDER_RATE_WINDOW_MS)).unref();

async function restoreState(){ if(!storageReady) return; const saved=await readJson(STATE_KEY,null); if(!saved||typeof saved!=='object') return; if(saved.menuVersion===MENU_VERSION&&Array.isArray(saved.products)&&saved.products.length) products.splice(0,products.length,...saved.products); if(Array.isArray(saved.orders)) orders.splice(0,orders.length,...saved.orders); if(Array.isArray(saved.customers)) customers.splice(0,customers.length,...saved.customers); if(Array.isArray(saved.reservations)) reservations.splice(0,reservations.length,...saved.reservations); }
const persistState=()=>void writeJson(STATE_KEY,{menuVersion:MENU_VERSION,products,orders,customers,reservations});
const restoreCategories=registerCategoryRoutes(app,{categories,products,storageReady,presign,readJson,writeJson,deleteObject,requireAdminApiKey,isAdminApiKeyValid});
const restoreStudio=registerStudioRoutes(app,{storageReady,presign,readJson,writeJson,deleteObject,requireAdminApiKey});
const nextProductId=()=>{const max=products.reduce((highest,product)=>Math.max(highest,Number(String(product.id).replace(/^P/,''))||0),0);return `P${String(max+1).padStart(3,'0')}`;};
const nextOrderId=()=>`O${String(orders.length+1).padStart(5,'0')}`;
const nextReservationId=()=>`R${String(reservations.length+1).padStart(4,'0')}`;

app.get('/health',(_req,res)=>res.json({ok:true,service:'arabisk-web',storageReady,persistentStorage:storageReady,menuVersion:MENU_VERSION,productCount:products.length,categoryCount:categories.length,orderCount:orders.length}));
app.get('/api/orders',requireAdminApiKey,(_req,res)=>res.json(orders));
app.get('/api/customers',requireAdminApiKey,(_req,res)=>res.json(customers));
app.get('/api/reservations',requireAdminApiKey,(_req,res)=>res.json(reservations));
app.patch('/api/orders/:id',requireAdminApiKey,(req,res)=>{const order=orders.find(item=>item.id===req.params.id);if(!order)return res.status(404).json({message:'Order not found'});const allowed=['pending','confirmed','preparing','ready','completed','cancelled'];if(req.body?.status!==undefined&&!allowed.includes(req.body.status))return res.status(400).json({message:'Invalid order status'});if(req.body?.status!==undefined)order.status=req.body.status;if(req.body?.notes!==undefined)order.notes=cleanText(req.body.notes,300);order.updatedAt=new Date().toISOString();persistState();return res.json(order);});

app.post('/api/reservations',reservationRateLimit,(req,res)=>{const b=req.body||{};const name=cleanText(b.name,80),phone=cleanText(b.phone,40),date=cleanText(b.date,20),time=cleanText(b.time,10),guests=Number(b.guests),notes=cleanText(b.notes,300);const dateOk=/^\d{4}-\d{2}-\d{2}$/.test(date);const timeOk=/^([01]\d|2[0-3]):[0-5]\d$/.test(time);const today=new Date().toISOString().slice(0,10);if(!name||!phone||!date||!time||!Number.isInteger(guests)||guests<1||guests>20)return res.status(400).json({message:'name, phone, date, time and guests are required'});if(!dateOk||date<today)return res.status(400).json({message:'Reservation date must be a valid date that is not in the past.'});if(!timeOk)return res.status(400).json({message:'Reservation time must be in HH:MM format.'});const reservation={id:nextReservationId(),name,phone,date,time,guests,notes,status:'pending',createdAt:new Date().toISOString()};reservations.push(reservation);persistState();return res.status(201).json(reservation);});
app.post('/api/orders',orderRateLimit,(req,res)=>{const b=req.body||{};const name=cleanText(b.name,80),phone=cleanText(b.phone,40),orderType=['dine_in','pickup'].includes(b.orderType)?b.orderType:'dine_in',tableNumber=orderType==='dine_in'?cleanText(b.tableNumber,30):'',notes=cleanText(b.notes,300);const rawItems=Array.isArray(b.items)?b.items:[];if(!name||phone.length<5||phone.length>40||!rawItems.length||rawItems.length>30)return res.status(400).json({message:'name, phone and at least one order item are required'});const merged=new Map();for(const raw of rawItems){const productId=cleanText(raw?.productId,40),quantity=Number(raw?.quantity);if(!productId||!Number.isInteger(quantity)||quantity<1||quantity>20)return res.status(400).json({message:'Invalid order item.'});const mergedQuantity=(merged.get(productId)||0)+quantity;if(mergedQuantity>20)return res.status(400).json({message:'Maximum quantity for a single item is 20.'});merged.set(productId,mergedQuantity);}const items=[];let total=0;for(const [productId,quantity] of merged){const product=products.find(item=>item.id===productId&&item.available!==false);if(!product)return res.status(400).json({message:'One or more selected items are no longer available.'});const unitPrice=Number(product.price);if(!Number.isFinite(unitPrice)||unitPrice<0)return res.status(400).json({message:'Invalid product price.'});const lineTotal=unitPrice*quantity;items.push({productId:product.id,nameAr:cleanText(product.nameAr,160),nameEn:cleanText(product.nameEn,160),quantity,unitPrice,lineTotal});total+=lineTotal;}const now=new Date().toISOString();const order={id:nextOrderId(),name,phone,orderType,tableNumber,notes,items,total,status:'pending',createdAt:now,updatedAt:now};orders.push(order);const existing=customers.find(customer=>customer.phone===phone);if(existing){existing.name=name;existing.lastOrderAt=now;existing.orderCount=Number(existing.orderCount||0)+1}else customers.push({id:crypto.randomUUID(),name,phone,orderCount:1,lastOrderAt:now});persistState();return res.status(201).json({id:order.id,total:order.total,status:order.status,orderType:order.orderType,tableNumber:order.tableNumber});});

app.patch('/api/reservations/:id',requireAdminApiKey,(req,res)=>{const reservation=reservations.find(item=>item.id===req.params.id);if(!reservation)return res.status(404).json({message:'Reservation not found'});if(req.body?.status!==undefined&&!['pending','confirmed','cancelled'].includes(req.body.status))return res.status(400).json({message:'Invalid reservation status'});if(req.body?.status!==undefined)reservation.status=req.body.status;if(req.body?.notes!==undefined)reservation.notes=cleanText(req.body.notes,300);persistState();return res.json(reservation);});

registerMediaRoutes(app,{products,storageReady,presign,requireAdminApiKey});
app.post('/api/videos/presign',requireAdminApiKey,(req,res)=>{if(!storageReady)return res.status(503).json({message:'Video storage is not configured on the web service.'});const productId=cleanText(req.body?.productId,40),fileName=cleanText(req.body?.fileName,160).replace(/[^a-zA-Z0-9._-]/g,'-'),contentType=cleanText(req.body?.contentType,80).toLowerCase(),size=Number(req.body?.size);if(!products.some(product=>product.id===productId))return res.status(404).json({message:'Product not found'});if(!fileName||!VIDEO_TYPES.has(contentType))return res.status(400).json({message:'Only MP4, WebM and MOV videos are supported.'});if(!Number.isFinite(size)||size<1||size>MAX_VIDEO_BYTES)return res.status(400).json({message:'Maximum video size is 120 MB.'});const key=`products/${productId}/${crypto.randomUUID()}-${fileName}`;try{return res.json({key,uploadUrl:presign('PUT',key,900),expiresIn:900});}catch(error){console.error(error);return res.status(503).json({message:'Unable to prepare video upload.'});}});
app.post('/api/videos/delete-presign',requireAdminApiKey,(req,res)=>{if(!storageReady)return res.status(503).json({message:'Video storage is not configured on the web service.'});const productId=cleanText(req.body?.productId,40),product=products.find(item=>item.id===productId);if(!product)return res.status(404).json({message:'Product not found'});if(!product.videoKey)return res.json({url:'',key:''});try{return res.json({url:presign('DELETE',product.videoKey,900),key:product.videoKey});}catch(error){console.error(error);return res.status(503).json({message:'Unable to prepare video deletion.'});}});

app.get('/api/products',(req,res)=>{const category=cleanText(req.query.category,80),search=cleanText(req.query.search,80).toLowerCase();let result=category?products.filter(product=>product.categoryId===category):products;if(search)result=result.filter(product=>`${product.nameAr} ${product.nameEn}`.toLowerCase().includes(search));if(!isAdminApiKeyValid(req))result=result.filter(product=>product.available!==false);return res.json(result.map(withMediaUrls));});
app.get('/api/products/:id',(req,res)=>{const product=products.find(item=>item.id===req.params.id);if(!product)return res.status(404).json({message:'Product not found'});if(product.available===false&&!isAdminApiKeyValid(req))return res.status(404).json({message:'Product not found'});return res.json(withMediaUrls(product));
});
app.post('/api/products',requireAdminApiKey,(req,res)=>{const {categoryId,nameAr,nameEn,descriptionAr='',descriptionEn='',imageUrl='',imageKey='',price,available=true,videoKey=''}=req.body||{};if(!categoryId||!nameAr||!nameEn||!Number.isFinite(Number(price)))return res.status(400).json({message:'categoryId, nameAr, nameEn and numeric price are required'});if(!categories.some(category=>category.id===categoryId))return res.status(400).json({message:'Unknown category'});const product={id:nextProductId(),categoryId,nameAr:cleanText(nameAr),nameEn:cleanText(nameEn),descriptionAr:cleanText(descriptionAr),descriptionEn:cleanText(descriptionEn),imageUrl:cleanUrl(imageUrl),imageKey:cleanKey(imageKey),price:Number(price),available:Boolean(available),videoKey:cleanKey(videoKey),sortOrder:products.length+1};products.push(product);persistState();return res.status(201).json(withMediaUrls(product));});
app.patch('/api/products/:id',requireAdminApiKey,(req,res)=>{const product=products.find(item=>item.id===req.params.id);if(!product)return res.status(404).json({message:'Product not found'});const b=req.body||{};const oldImageKey=product.imageKey;const oldVideoKey=product.videoKey;if(b.categoryId!==undefined){if(!categories.some(category=>category.id===b.categoryId))return res.status(400).json({message:'Unknown category'});product.categoryId=b.categoryId;}if(b.nameAr!==undefined)product.nameAr=cleanText(b.nameAr);if(b.nameEn!==undefined)product.nameEn=cleanText(b.nameEn);if(b.descriptionAr!==undefined)product.descriptionAr=cleanText(b.descriptionAr);if(b.descriptionEn!==undefined)product.descriptionEn=cleanText(b.descriptionEn);if(b.imageUrl!==undefined)product.imageUrl=cleanUrl(b.imageUrl);if(b.imageKey!==undefined)product.imageKey=cleanKey(b.imageKey);if(b.price!==undefined){if(!Number.isFinite(Number(b.price)))return res.status(400).json({message:'Price must be numeric'});product.price=Number(b.price);}if(b.available!==undefined)product.available=Boolean(b.available);if(b.videoKey!==undefined)product.videoKey=cleanKey(b.videoKey);if(storageReady&&b.imageKey!==undefined&&oldImageKey&&oldImageKey!==product.imageKey)void deleteObject(oldImageKey);if(storageReady&&b.videoKey!==undefined&&oldVideoKey&&oldVideoKey!==product.videoKey)void deleteObject(oldVideoKey);persistState();return res.json(withMediaUrls(product));});
app.delete('/api/products/:id',requireAdminApiKey,(req,res)=>{const index=products.findIndex(product=>product.id===req.params.id);if(index===-1)return res.status(404).json({message:'Product not found'});const [removed]=products.splice(index,1);if(storageReady){if(removed.imageKey)void deleteObject(removed.imageKey);if(removed.videoKey)void deleteObject(removed.videoKey);}persistState();return res.json({ok:true,removed});});

app.get('/menu',(req,res)=>res.sendFile(path.join(__dirname,'menu.html')));
app.get(/^\/menu\/[^/]+$/,(req,res)=>res.sendFile(path.join(__dirname,'category-page.html')));
app.get(/^\/menu\/[^/]+\/[^/]+$/,(req,res)=>res.sendFile(path.join(__dirname,'product-page.html')));

app.use(express.static(dist));app.use((_req,res)=>res.sendFile(path.join(dist,'index.html')));app.use((error,_req,res,_next)=>{console.error('ARABISK web error:',error);if(!res.headersSent)res.status(500).json({message:'Internal server error'});});
await restoreState();await restoreCategories();await restoreStudio();if(storageReady)persistState();app.listen(port,()=>console.log(`ARABISK web listening on ${port} — ${products.length} menu items, ${categories.length} categories`));
