const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const slug=(v)=>String(v??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const MENU_CACHE_KEY='arabisk-menu-cache-v1';const MENU_CACHE_TTL=10000;
const readMenuCache=()=>{try{const value=JSON.parse(sessionStorage.getItem(MENU_CACHE_KEY)||'null');return value&&value.savedAt&&Date.now()-value.savedAt<MENU_CACHE_TTL&&Array.isArray(value.categories)&&Array.isArray(value.products)?value:null}catch{return null}};
const writeMenuCache=(categories,products)=>{try{sessionStorage.setItem(MENU_CACHE_KEY,JSON.stringify({savedAt:Date.now(),categories,products}))}catch{}};
const api=async(url)=>{const cached=readMenuCache();if(cached){if(url==='/api/categories')return cached.categories;if(url==='/api/products')return cached.products}const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error('request failed');return response.json()};
const pathParts=decodeURIComponent(location.pathname.replace(/\/$/,'')).split('/');
const categorySlug=pathParts[2]||'';
const root=document.querySelector('#grid');
const search=document.querySelector('#menu-search');
const sort=document.querySelector('#sort');
const count=document.querySelector('#result-count');
if(!root||!search||!sort||!count||!categorySlug)throw new Error('smart menu target not found');
let items=[];let category=null;let mode='all';let priceFilter='all';
const chipWrap=document.querySelector('#price-filters');
if(chipWrap){chipWrap.insertAdjacentHTML('afterend','<div class="smart-filters" id="smart-filters" aria-label="الفلاتر الذكية"></div>');}
const smartFilters=document.querySelector('#smart-filters');
const smartOptions=[['all','كل الخيارات'],['popular','🔥 الأكثر طلبًا'],['new','جديد'],['spicy','حار'],['vegetarian','نباتي'],['glutenFree','بدون جلوتين'],['chefChoice','Chef\'s Choice']];
function availableSmartOptions(){return smartOptions.filter(([key])=>key==='all'||items.some(item=>item.smart?.[key]));}
function renderSmartFilters(){if(!smartFilters)return;smartFilters.innerHTML=availableSmartOptions().map(([key,label])=>`<button class="chip ${mode===key?'active':''}" data-smart="${key}" type="button">${label}</button>`).join('');smartFilters.querySelectorAll('[data-smart]').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.smart;renderSmartFilters();render()}));}
function badgeText(item){const badges=[];if(item.smart?.popular)badges.push('<span>الأكثر طلبًا</span>');if(item.smart?.isNew)badges.push('<span>جديد</span>');if(item.smart?.chefChoice)badges.push('<span>اختيار الشيف</span>');return badges.length?`<div class="smart-badges">${badges.join('')}</div>`:'';}
function matches(item){const text=`${item.nameAr||''} ${item.nameEn||''}`.toLowerCase();const q=search.value.trim().toLowerCase();if(q&&!text.includes(q))return false;const price=Number(item.price)||0;if(priceFilter==='under50'&&price>=50)return false;if(priceFilter==='50to100'&&(price<50||price>100))return false;if(priceFilter==='over100'&&price<=100)return false;if(mode!=='all'&&!item.smart?.[mode])return false;return item.available!==false;}
function list(){const result=items.filter(matches);if(sort.value==='priceAsc')result.sort((a,b)=>Number(a.price)-Number(b.price));if(sort.value==='priceDesc')result.sort((a,b)=>Number(b.price)-Number(a.price));if(sort.value==='name')result.sort((a,b)=>String(a.nameAr||a.nameEn).localeCompare(String(b.nameAr||b.nameEn),'ar'));if(sort.value==='popular')result.sort((a,b)=>Number(Boolean(b.smart?.popular))-Number(Boolean(a.smart?.popular)));return result;}
async function loadCartRuntime(){if(window.ARABISK_CART)return true;if(cartRuntimePromise)return cartRuntimePromise;cartRuntimePromise=new Promise(resolve=>{const script=document.createElement('script');script.src='/cart.js?v=20260920.6';script.onload=()=>resolve(Boolean(window.ARABISK_CART));script.onerror=()=>resolve(false);document.head.appendChild(script);setTimeout(()=>resolve(Boolean(window.ARABISK_CART)),5000)});return cartRuntimePromise}
async function addToCart(button){const product=items.find(item=>String(item.id)===String(button.dataset.smartAdd));if(!product)return;const previous=button.textContent;button.disabled=true;try{if(!window.ARABISK_CART?.add)throw new Error('cart runtime unavailable');await (window.ARABISK_CART.ready?.()||Promise.resolve());if(!window.ARABISK_CART.add(product))throw new Error('cart add rejected');button.textContent='تمت الإضافة ✓';setTimeout(()=>{button.textContent=previous;button.disabled=false},1400)}catch(error){console.error('ARABISK cart add:',error);button.textContent='تعذر الإضافة';setTimeout(()=>{button.textContent=previous;button.disabled=false},1800)}}}
function render(){const visible=list();count.textContent=`${visible.length} صنف`;root.innerHTML=visible.map(item=>{const href=`/menu/${slug(category.id)}/${slug(item.nameEn||item.nameAr)}`;const visual=item.imageUrl||'';return `<article class="item"><a class="item-link" href="${href}"><div>${visual?`<img class="item-thumb" src="${esc(visual)}" alt="${esc(item.nameAr||item.nameEn)}" loading="lazy" decoding="async" fetchpriority="low" onerror="this.remove()">`:''}${badgeText(item)}<span class="cat">${esc(item.nameEn)}</span><h3>${esc(item.nameAr||item.nameEn)}</h3><p>${esc(item.descriptionAr||'اختيار مميز من قائمة ARABISK.')}</p></div></a><div class="item-bottom"><div class="price">AED ${Number(item.price).toFixed(0)}</div><div class="item-actions"><a class="item-open" href="${href}">التفاصيل ←</a><button class="add-btn" type="button" data-smart-add="${esc(item.id)}">إضافة للطلب</button></div></div></article>`}).join('')||'<p class="empty-menu">لا توجد أصناف مطابقة للفلاتر الحالية.</p>';root.querySelectorAll('[data-smart-add]').forEach(button=>button.addEventListener('click',()=>void addToCart(button)));}
search.addEventListener('input',render);sort.addEventListener('change',render);
if(chipWrap)chipWrap.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{priceFilter=button.dataset.filter;chipWrap.querySelectorAll('[data-filter]').forEach(item=>item.classList.toggle('active',item===button));render()}));
(async()=>{try{const cached=readMenuCache();const [categories,products]=cached?[cached.categories,cached.products]:await Promise.all([api('/api/categories'),api('/api/products')]);if(!cached)writeMenuCache(categories,products);category=categories.find(item=>slug(item.id)===categorySlug);if(!category||category.active===false){location.assign('/menu');return}items=products.filter(item=>item.categoryId===category.id&&item.available!==false);document.title=`${category.nameAr||category.nameEn} — ARABISK`;const eyebrow=document.querySelector('#detail-eyebrow');const title=document.querySelector('#detail-title');const lead=document.querySelector('#detail-lead');if(eyebrow)eyebrow.textContent=(category.nameEn||'MENU').toUpperCase();if(title)title.textContent=category.nameAr||category.nameEn;if(lead)lead.textContent=`استكشف أصناف ${category.nameAr||category.nameEn} واختر ما يناسبك.`;renderSmartFilters();render()}catch(error){console.error('ARABISK smart menu:',error)}})();
