const $=(selector)=>document.querySelector(selector);
const apiBase=()=>((localStorage.getItem('ARABISK_API_BASE')||window.ARABISK_API_BASE||import.meta.env.VITE_API_BASE_URL||(import.meta.env.DEV?'http://localhost:3000':'/proxy')).replace(/\/$/,''));
let products=[],categories=[],orders=[],customers=[],reservations=[],editingId=null;
const categoryName=(id)=>categories.find(c=>c.id===id)?.nameAr||id;
const escapeHtml=(value)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const orderStatusLabel={pending:'قيد المراجعة',confirmed:'مؤكد',preparing:'قيد التحضير',ready:'جاهز',completed:'مكتمل',cancelled:'ملغي'};
const statusClass=(status)=>status==='confirmed'||status==='ready'||status==='completed'?'on':status==='cancelled'?'off':'pending';
async function request(path,options={}){const response=await fetch(`${apiBase()}${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'حدث خطأ أثناء الاتصال بالخادم');return data;}
function renderStats(){$('#count-products').textContent=products.length;$('#count-categories').textContent=categories.length;$('#count-available').textContent=products.filter(p=>p.available).length;$('#count-reservations').textContent=reservations.length;$('#count-orders').textContent=orders.length;}
function renderProducts(){const query=$('#search').value.trim().toLowerCase();const filtered=products.filter(p=>!query||`${p.nameAr} ${p.nameEn}`.toLowerCase().includes(query));$('#products-body').innerHTML=filtered.map(p=>`<tr><td>${p.imageUrl?`<img class="product-thumb" src="${escapeHtml(p.imageUrl)}" alt="" loading="lazy">`:''}<strong>${escapeHtml(p.nameAr)}</strong><small>${escapeHtml(p.nameEn)}</small></td><td>${escapeHtml(categoryName(p.categoryId))}</td><td class="price">AED ${Number(p.price).toFixed(0)}</td><td>${p.videoKey?'<span class="status on">متوفر</span>':'<span class="status off">غير مضاف</span>'}</td><td><span class="status ${p.available?'on':'off'}">${p.available?'متاح':'مخفي'}</span></td><td class="actions"><button data-video="${p.id}">فيديو</button><button data-edit="${p.id}">تعديل</button><button data-delete="${p.id}" class="danger">حذف</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد أصناف</td></tr>';}
function renderCategories(){$('#categories-body').innerHTML=categories.map((c,index)=>`<tr><td>${index+1}</td><td><strong>${escapeHtml(c.nameAr)}</strong></td><td>${escapeHtml(c.nameEn)}</td><td><span class="status ${c.active?'on':'off'}">${c.active?'نشط':'مخفي'}</span></td></tr>`).join('')||'<tr><td colspan="4" class="empty">لا توجد أقسام</td></tr>';}
function renderReservations(){const rows=reservations.map(r=>`<tr><td><strong>${escapeHtml(r.name)}</strong><small>${r.eventSlug?`فعالية: ${escapeHtml(r.eventSlug)}`:(r.notes?escapeHtml(r.notes):'—')}</small></td><td>${escapeHtml(r.date)}<small>${escapeHtml(r.time)}</small></td><td>${Number(r.guests)}</td><td dir="ltr">${escapeHtml(r.phone)}</td><td><span class="status ${r.status==='confirmed'?'on':r.status==='cancelled'?'off':'pending'}">${r.status==='confirmed'?'مؤكد':r.status==='cancelled'?'ملغي':'قيد المراجعة'}</span></td><td class="actions"><button data-res-status="confirmed" data-id="${r.id}">تأكيد</button><button data-res-status="cancelled" data-id="${r.id}" class="danger">إلغاء</button></td></tr>`).join('');$('#reservations-body').innerHTML=rows||'<tr><td colspan="6" class="empty">لا توجد حجوزات حاليًا.</td></tr>';}
function renderOrders(){const body=$('#orders-body');if(!orders.length){body.innerHTML='';$('#orders-state').textContent='لا توجد طلبات مسجلة حاليًا.';return}$('#orders-state').textContent=`${orders.length} طلب مسجل.`;body.innerHTML=orders.map(order=>{const items=(order.items||[]).map(item=>`${escapeHtml(item.nameAr)} × ${Number(item.quantity)}`).join('، ');const orderType=order.orderType==='pickup'?'استلام':'داخل المطعم';const location=order.tableNumber?`<small>طاولة ${escapeHtml(order.tableNumber)}</small>`:'';return `<tr><td><strong>${escapeHtml(order.id)}</strong><small>${new Date(order.createdAt).toLocaleString('ar-AE')}</small></td><td><strong>${escapeHtml(order.name)}</strong><small dir="ltr">${escapeHtml(order.phone)}</small></td><td><small>${items}</small></td><td class="price">AED ${Number(order.total).toFixed(0)}</td><td><strong>${orderType}</strong>${location}</td><td><span class="status ${statusClass(order.status)}">${orderStatusLabel[order.status]||order.status}</span></td><td class="actions"><select data-order-status="${escapeHtml(order.id)}"><option value="pending">قيد المراجعة</option><option value="confirmed">مؤكد</option><option value="preparing">قيد التحضير</option><option value="ready">جاهز</option><option value="completed">مكتمل</option><option value="cancelled">ملغي</option></select></td></tr>`}).join('');orders.forEach(order=>{const select=document.querySelector(`select[data-order-status="${CSS.escape(order.id)}"]`);if(select)select.value=order.status});}
function renderCustomers(){
  const state=$('#customers-state');
  const body=$('#customers-body');
  if(!customers.length){if(state)state.textContent='لا توجد بيانات عملاء مسجلة حاليًا.';if(body)body.innerHTML='';return;}
  if(state)state.textContent=`${customers.length} عميل مسجل.`;
  if(body)body.innerHTML=customers.map(customer=>`<tr><td><strong>${escapeHtml(customer.name||'عميل')}</strong><small dir="ltr">${escapeHtml(customer.phone||'')}</small></td><td>${Number(customer.orderCount||0)}</td><td>${Number(customer.reservationCount||0)}</td><td>${customer.lastOrderAt?new Date(customer.lastOrderAt).toLocaleDateString('ar-AE'):'—'}</td><td class="actions"><button class="small-action" data-customer-360="${escapeHtml(customer.id)}" type="button">فتح الملف</button></td></tr>`).join('');
}
function openModal(product=null){editingId=product?.id||null;$('#modal-title').textContent=editingId?'تعديل الصنف':'إضافة صنف جديد';$('#name-ar').value=product?.nameAr||'';$('#name-en').value=product?.nameEn||'';$('#price').value=product?.price??'';$('#image-url').value=product?.imageUrl&&!product.imageKey?product.imageUrl:'';$('#description-ar').value=product?.descriptionAr||'';$('#category').innerHTML=categories.map(c=>`<option value="${escapeHtml(c.id)}" ${product?.categoryId===c.id?'selected':''}>${escapeHtml(c.nameAr)}</option>`).join('');$('#available').checked=product?.available??true;$('#video-file').value='';$('#selected-file').textContent='';$('#remove-video').hidden=!product?.videoKey;updateVideoPreview(product?.videoUrl||'');$('#image-file').value='';$('#selected-image').textContent='';$('#remove-image').hidden=!product?.imageKey;updateImagePreview(product?.imageUrl||'');$('#modal').classList.add('show');$('#modal').setAttribute('aria-hidden','false');$('#name-ar').focus();}
function closeModal(){$('#modal').classList.remove('show');$('#modal').setAttribute('aria-hidden','true');editingId=null;}
function updateVideoPreview(url){const wrap=$('#video-preview'),player=$('#video-preview-player');if(!url){wrap.hidden=true;player.removeAttribute('src');player.load();return}player.src=url;wrap.hidden=false;}
function updateImagePreview(url){const wrap=$('#image-preview'),image=$('#image-preview-player');if(!url){wrap.hidden=true;image.removeAttribute('src');return}image.src=url;wrap.hidden=false;}
function showSection(sectionId){document.querySelectorAll('.admin-section').forEach(s=>s.classList.remove('section-visible'));document.querySelectorAll('[data-section]').forEach(link=>link.classList.toggle('active',link.dataset.section===sectionId));const titleMap={dashboard:'إدارة ARABISK',products:'إدارة الأصناف',categories:'إدارة الأقسام',studio:'ARABISK Studio — العروض',experiences:'الفعاليات والتجارب',reservations:'حجوزات الطاولات',orders:'الطلبات',revenue:'فرص الإيراد',customers:'العملاء',settings:'إعدادات الموقع'};$('#page-title').textContent=titleMap[sectionId]||'إدارة ARABISK';$('#dashboard-stats').style.display=sectionId==='dashboard'?'grid':'none';const section=document.getElementById(sectionId==='dashboard'?'products':sectionId);if(section)section.classList.add('section-visible');if(sectionId==='dashboard')document.getElementById('products').classList.add('section-visible');}
async function load(){ $('#connection').textContent='جارٍ الاتصال…';try{const results=await Promise.all([request('/api/categories'),request('/api/products'),request('/api/orders'),request('/api/customers'),request('/api/reservations')]);[categories,products,orders,customers,reservations]=results;renderStats();renderProducts();renderCategories();renderOrders();renderCustomers();renderReservations();$('#connection').textContent='متصل';$('#connection').className='connected';$('#error').textContent='';}catch(error){$('#connection').textContent='غير متصل';$('#connection').className='disconnected';$('#error').textContent=`${error.message}. تحقق من رابط الـAPI في الإعدادات.`;}}
function loadSettings(){$('#api-base').value=apiBase();$('#site-name').value=localStorage.getItem('ARABISK_SITE_NAME')||'ARABISK';$('#site-description').value=localStorage.getItem('ARABISK_SITE_DESCRIPTION')||'مطعم وكافيه بطابع عربي عصري.';}
async function uploadFile(endpoint,productId,file,onProgress,errorText){const prepared=await request(endpoint,{method:'POST',body:JSON.stringify({productId,fileName:file.name,contentType:file.type,size:file.size})});await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',prepared.uploadUrl);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.upload.onprogress=event=>{if(event.lengthComputable&&onProgress)onProgress(Math.round(event.loaded/event.total*100))};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error(errorText));xhr.onerror=()=>reject(new Error('تعذر الاتصال بتخزين الوسائط.'));xhr.send(file)});return prepared.key;}
async function deleteVideo(productId){const prepared=await request('/api/videos/delete-presign',{method:'POST',body:JSON.stringify({productId})});if(prepared.url){const response=await fetch(prepared.url,{method:'DELETE'});if(!response.ok)throw new Error('تعذر حذف الفيديو من التخزين.')}await request(`/api/products/${productId}`,{method:'PATCH',body:JSON.stringify({videoKey:''})});}
async function deleteImage(productId){const prepared=await request('/api/images/delete-presign',{method:'POST',body:JSON.stringify({productId})});if(prepared.url){const response=await fetch(prepared.url,{method:'DELETE'});if(!response.ok)throw new Error('تعذر حذف الصورة من التخزين.')}await request(`/api/products/${productId}`,{method:'PATCH',body:JSON.stringify({imageKey:''})});}
document.querySelectorAll('[data-section]').forEach(link=>link.addEventListener('click',()=>setTimeout(()=>showSection(link.dataset.section),0)));
$('#add-product').addEventListener('click',()=>openModal());$('#cancel').addEventListener('click',closeModal);$('#search').addEventListener('input',renderProducts);$('#refresh-reservations').addEventListener('click',load);$('#refresh-orders').addEventListener('click',load);$('#modal').addEventListener('click',event=>{if(event.target.id==='modal')closeModal()});
$('#video-file').addEventListener('change',()=>{const file=$('#video-file').files[0];if(!file){$('#selected-file').textContent='';return}$('#selected-file').textContent=`${file.name} — ${(file.size/1024/1024).toFixed(1)} MB`;if($('#video-preview-player').src.startsWith('blob:'))URL.revokeObjectURL($('#video-preview-player').src);updateVideoPreview(URL.createObjectURL(file));$('#remove-video').hidden=false});
$('#image-file').addEventListener('change',()=>{const file=$('#image-file').files[0];if(!file){$('#selected-image').textContent='';return}$('#selected-image').textContent=`${file.name} — ${(file.size/1024/1024).toFixed(1)} MB`;updateImagePreview(URL.createObjectURL(file));$('#remove-image').hidden=false});
$('#remove-video').addEventListener('click',async()=>{if(!editingId||!confirm('حذف فيديو التحضير لهذا المنتج؟'))return;try{await deleteVideo(editingId);const p=products.find(x=>x.id===editingId);if(p){p.videoKey='';p.videoUrl=''}$('#video-file').value='';$('#selected-file').textContent='';$('#remove-video').hidden=true;updateVideoPreview('');renderProducts()}catch(error){alert(error.message)}});
$('#remove-image').addEventListener('click',async()=>{if(!editingId||!confirm('حذف صورة هذا المنتج؟'))return;try{await deleteImage(editingId);const p=products.find(x=>x.id===editingId);if(p){p.imageKey='';p.imageUrl=''}$('#image-file').value='';$('#selected-image').textContent='';$('#remove-image').hidden=true;updateImagePreview('');renderProducts()}catch(error){alert(error.message)}});
$('#products-body').addEventListener('click',async(event)=>{const edit=event.target.dataset.edit,del=event.target.dataset.delete,video=event.target.dataset.video;if(edit)return openModal(products.find(p=>p.id===edit));if(video){const product=products.find(p=>p.id===video);if(!product?.videoUrl)return alert('لا يوجد فيديو تحضير مضاف لهذا الصنف.');window.open(product.videoUrl,'_blank','noopener');return}if(del){const product=products.find(p=>p.id===del);if(!product||!confirm(`حذف «${product.nameAr}»؟`))return;try{await request(`/api/products/${del}`,{method:'DELETE'});await load()}catch(error){alert(error.message)}}});
$('#reservations-body').addEventListener('click',async event=>{const id=event.target.dataset.id,status=event.target.dataset.resStatus;if(!id||!status)return;try{await request(`/api/reservations/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(error){alert(error.message)}});
$('#orders-body').addEventListener('change',async event=>{const id=event.target.dataset.orderStatus;if(!id)return;try{await request(`/api/orders/${id}`,{method:'PATCH',body:JSON.stringify({status:event.target.value})});await load()}catch(error){alert(error.message);await load()}});
$('#product-form').addEventListener('submit',async event=>{event.preventDefault();const submit=$('#product-form .submit'),progress=$('#upload-progress');submit.disabled=true;try{const payload={categoryId:$('#category').value,nameAr:$('#name-ar').value,nameEn:$('#name-en').value,descriptionAr:$('#description-ar').value,imageUrl:$('#image-url').value.trim(),price:Number($('#price').value),available:$('#available').checked};let saved=editingId?await request(`/api/products/${editingId}`,{method:'PATCH',body:JSON.stringify(payload)}):await request('/api/products',{method:'POST',body:JSON.stringify(payload)});const imageFile=$('#image-file').files[0];if(imageFile){if(imageFile.size>15*1024*1024)throw new Error('الحد الأقصى للصورة 15MB.');if(!['image/jpeg','image/png','image/webp','image/avif'].includes(imageFile.type))throw new Error('الصيغ المسموحة: JPG وPNG وWebP وAVIF.');progress.hidden=false;progress.querySelector('span').style.width='0%';progress.querySelector('small').textContent='جاري رفع الصورة… 0%';const key=await uploadFile('/api/images/presign',saved.id,imageFile,percent=>{progress.querySelector('span').style.width=`${percent}%`;progress.querySelector('small').textContent=`جاري رفع الصورة… ${percent}%`},'فشل رفع الصورة إلى التخزين.');saved=await request(`/api/products/${saved.id}`,{method:'PATCH',body:JSON.stringify({imageKey:key,imageUrl:''})})}const file=$('#video-file').files[0];if(file){if(file.size>120*1024*1024)throw new Error('الحد الأقصى للفيديو 120MB.');if(!['video/mp4','video/webm','video/quicktime'].includes(file.type))throw new Error('الصيغ المسموحة: MP4 وWebM وMOV.');progress.hidden=false;progress.querySelector('span').style.width='0%';progress.querySelector('small').textContent='جاري رفع الفيديو… 0%';const key=await uploadFile('/api/videos/presign',saved.id,file,percent=>{progress.querySelector('span').style.width=`${percent}%`;progress.querySelector('small').textContent=`جاري رفع الفيديو… ${percent}%`},'فشل رفع الفيديو إلى التخزين.');await request(`/api/products/${saved.id}`,{method:'PATCH',body:JSON.stringify({videoKey:key})})}progress.hidden=true;closeModal();await load()}catch(error){progress.hidden=true;alert(error.message)}finally{submit.disabled=false}});
$('#settings-form').addEventListener('submit',event=>{event.preventDefault();localStorage.setItem('ARABISK_API_BASE',$('#api-base').value.trim().replace(/\/$/,''));localStorage.setItem('ARABISK_SITE_NAME',$('#site-name').value.trim());localStorage.setItem('ARABISK_SITE_DESCRIPTION',$('#site-description').value.trim());$('#settings-message').textContent='تم حفظ الإعدادات.';setTimeout(()=>$('#settings-message').textContent='',2500);load()});
loadSettings();showSection(location.hash.replace('#','')||'dashboard');load();

async function openCustomer360(customerId){
  const modal=$('#customer360-modal');
  const body=$('#customer360-body');
  if(!modal||!body)return;
  modal.classList.add('show');
  modal.setAttribute('aria-hidden','false');
  body.innerHTML='<p class="empty">جارٍ تحميل ملف العميل…</p>';
  try{
    const profile=await request('/api/revenue/customers/'+encodeURIComponent(customerId)+'/360');
    const customer=profile.customer||{};
    const summary=profile.summary||{};
    const money=value=>'AED '+Number(value||0).toFixed(0);
    const opps=(profile.opportunities||[]).map(item=>`<div class="customer360-opportunity"><strong>${escapeHtml(item.priority||'—')}</strong><span>${escapeHtml(item.reason||item.recommendedAction||'فرصة مرتبطة بالعميل')}</span></div>`).join('')||'<div class="empty">لا توجد فرص مرتبطة حاليًا.</div>';
    const orders=(profile.orders||[]).map(order=>`<tr><td><strong>${escapeHtml(order.id)}</strong><small>${new Date(order.createdAt).toLocaleString('ar-AE')}</small></td><td class="price">${money(order.total)}</td><td>${escapeHtml(order.status)}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">لا توجد طلبات.</td></tr>';
    const reservations=(profile.reservations||[]).map(item=>`<tr><td>${escapeHtml(item.date)}<small>${escapeHtml(item.time)}</small></td><td>${Number(item.guests||0)}</td><td>${escapeHtml(item.status)}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">لا توجد حجوزات.</td></tr>';
    body.innerHTML=`<div class="customer360-head"><div><span>Customer 360</span><h2>${escapeHtml(customer.name||'عميل')}</h2><small dir="ltr">${escapeHtml(customer.phone||'')}</small></div><span class="status ${customer.marketingOptIn?'on':'pending'}">${customer.marketingOptIn?'موافقة تواصل موجودة':'لا توجد موافقة تسويقية'}</span></div><div class="customer360-stats"><article><span>الطلبات</span><b>${Number(customer.orderCount||0)}</b></article><article><span>قيمة الطلبات</span><b>${money(summary.totalOrderValue)}</b></article><article><span>الحجوزات</span><b>${Number(summary.totalReservations||0)}</b></article><article><span>آخر نشاط</span><b class="customer360-date">${summary.lastActivityAt?new Date(summary.lastActivityAt).toLocaleString('ar-AE'):'—'}</b></article></div><div class="customer360-columns"><div><h3>الطلبات</h3><div class="table-wrap"><table><thead><tr><th>الطلب</th><th>القيمة</th><th>الحالة</th></tr></thead><tbody>${orders}</tbody></table></div></div><div><h3>الحجوزات</h3><div class="table-wrap"><table><thead><tr><th>الموعد</th><th>الأشخاص</th><th>الحالة</th></tr></thead><tbody>${reservations}</tbody></table></div></div></div><div class="customer360-opportunities"><h3>الفرص المرتبطة</h3>${opps}</div>`;
  }catch(error){body.innerHTML=`<p class="empty">${escapeHtml(error.message)}</p>`;}
}
function closeCustomer360(){const modal=$('#customer360-modal');if(!modal)return;modal.classList.remove('show');modal.setAttribute('aria-hidden','true');}
document.addEventListener('click',event=>{
  const button=event.target.closest('[data-customer-360]');
  if(button)void openCustomer360(button.dataset.customer360);
  if(event.target.closest('#customer360-close'))closeCustomer360();
});
