const $=s=>document.querySelector(s);
const apiBase=()=>((localStorage.getItem('ARABISK_API_BASE')||window.ARABISK_API_BASE||import.meta.env.VITE_API_BASE_URL||(import.meta.env.DEV?'http://localhost:3000':'/proxy')).replace(/\/$/,''));
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
let experiences=[],editingId=null;
const labels={draft:'مسودة',published:'منشورة',closed:'مغلقة',archived:'مؤرشفة'};
const request=async(path,options={})=>{const r=await fetch(apiBase()+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'تعذر الاتصال بالخادم');return d};
const fmt=v=>{const d=new Date(v);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('ar-AE',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d):'—'};
const dateTimeLocal=v=>{const d=new Date(v);if(!Number.isFinite(d.getTime()))return '';const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
const MAX_VIDEO_BYTES=120*1024*1024;
const VIDEO_TYPES=['video/mp4','video/webm','video/quicktime'];
const render=()=>{$('#experiences-body').innerHTML=experiences.map(item=>'<tr><td>'+(item.coverImageUrl?'<img class="event-admin-thumb" src="'+esc(item.coverImageUrl)+'" alt="" loading="lazy">':'')+'<strong>'+esc(item.titleAr)+'</strong><small>'+esc(item.titleEn)+'</small></td><td>'+esc(item.location||'—')+'</td><td>'+esc(fmt(item.startsAt))+'</td><td class="price">'+(Number(item.price)>0?'AED '+Number(item.price).toFixed(0):'مجاني')+'</td><td><span class="status '+(item.status==='published'?'on':item.status==='closed'?'off':'pending')+'">'+(labels[item.status]||item.status)+'</span></td><td class="actions"><a href="/events/'+encodeURIComponent(item.slug)+'" target="_blank" rel="noopener">عرض</a><button data-edit="'+item.id+'">تعديل</button><button data-toggle="'+item.id+'">'+(item.status==='published'?'إخفاء':'نشر')+'</button><button class="danger" data-delete="'+item.id+'">حذف</button></td></tr>').join('')||'<tr><td colspan="6" class="empty">لا توجد فعاليات بعد.</td></tr>'};
const openModal=item=>{editingId=item?.id||null;$('#experience-modal-title').textContent=editingId?'تعديل الفعالية':'إضافة فعالية';$('#e-title-ar').value=item?.titleAr||'';$('#e-title-en').value=item?.titleEn||'';$('#e-slug').value=item?.slug||'';$('#e-type').value=item?.type||'event';$('#e-start').value=item?.startsAt?dateTimeLocal(item.startsAt):'';$('#e-end').value=item?.endsAt?dateTimeLocal(item.endsAt):'';$('#e-location').value=item?.location||'';$('#e-capacity').value=item?.capacity||'';$('#e-price').value=item?.price??0;$('#e-description').value=item?.descriptionAr||'';$('#e-image-url').value=item?.coverImageUrl&&!item.coverImageKey?item.coverImageUrl:'';$('#e-status').value=item?.status||'draft';$('#e-featured').checked=item?.featured??false;$('#e-booking').checked=item?.bookingEnabled??true;$('#e-image-file').value='';$('#e-selected-image').textContent='';$('#e-video-file').value='';$('#e-selected-video').textContent='';$('#e-remove-video').hidden=!item?.videoKey;updateVideoPreview(item?.videoUrl||'');$('#experience-modal').classList.add('show');$('#experience-modal').setAttribute('aria-hidden','false');$('#e-title-ar').focus()};
const closeModal=()=>{$('#experience-modal').classList.remove('show');$('#experience-modal').setAttribute('aria-hidden','true');editingId=null};
const load=async()=>{try{experiences=await request('/api/experiences');render();$('#experiences-message').textContent=experiences.length+' فعالية مسجلة.'}catch(error){$('#experiences-message').textContent=error.message}};
$('#add-experience').addEventListener('click',()=>openModal());$('#experience-cancel').addEventListener('click',closeModal);$('#experience-modal').addEventListener('click',e=>{if(e.target.id==='experience-modal')closeModal()});$('#experience-refresh').addEventListener('click',load);
$('#experiences-body').addEventListener('click',async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete,toggle=e.target.dataset.toggle;if(edit){openModal(experiences.find(x=>x.id===edit));return}if(del){const item=experiences.find(x=>x.id===del);if(!item||!confirm('حذف «'+item.titleAr+'»؟'))return;try{await request('/api/experiences/'+del,{method:'DELETE'});await load()}catch(error){alert(error.message)}}if(toggle){const item=experiences.find(x=>x.id===toggle);if(!item)return;try{await request('/api/experiences/'+toggle,{method:'PATCH',body:JSON.stringify({status:item.status==='published'?'closed':'published'})});await load()}catch(error){alert(error.message)}}});
async function uploadVideo(experienceId,file,onProgress){const prepared=await request('/api/experiences/videos/presign',{method:'POST',body:JSON.stringify({experienceId,fileName:file.name,contentType:file.type,size:file.size})});await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',prepared.uploadUrl);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable&&onProgress)onProgress(Math.round(e.loaded/e.total*100))};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error('فشل رفع فيديو الفعالية.'));xhr.onerror=()=>reject(new Error('تعذر الاتصال بتخزين الفيديو.'));xhr.send(file)});return prepared.key}
async function deleteVideo(experienceId){const prepared=await request('/api/experiences/videos/delete-presign',{method:'POST',body:JSON.stringify({experienceId})});if(prepared.url){const response=await fetch(prepared.url,{method:'DELETE'});if(!response.ok)throw new Error('تعذر حذف الفيديو من التخزين.')}await request('/api/experiences/'+experienceId,{method:'PATCH',body:JSON.stringify({videoKey:''})})}
const updateVideoPreview=url=>{const wrap=$('#e-video-preview'),player=$('#e-video-preview-player');if(!url){wrap.hidden=true;player.removeAttribute('src');player.load();return}player.src=url;wrap.hidden=false};
$('#e-video-file').addEventListener('change',()=>{const file=$('#e-video-file').files[0];if(!file){$('#e-selected-video').textContent='';return}$('#e-selected-video').textContent=file.name+' — '+(file.size/1024/1024).toFixed(1)+' MB';updateVideoPreview(URL.createObjectURL(file));$('#e-remove-video').hidden=false});
$('#e-remove-video').addEventListener('click',async()=>{if(!editingId){$('#e-video-file').value='';$('#e-selected-video').textContent='';$('#e-remove-video').hidden=true;updateVideoPreview('');return}if(!confirm('حذف فيديو هذه الفعالية؟'))return;try{await deleteVideo(editingId);$('#e-video-file').value='';$('#e-selected-video').textContent='';$('#e-remove-video').hidden=true;updateVideoPreview('')}catch(error){alert(error.message)}});
$('#experience-form').addEventListener('submit',async e=>{e.preventDefault();const button=$('#experience-form .submit');button.disabled=true;try{const start=$('#e-start').value;if(!start)throw new Error('حدد موعد بداية الفعالية.');const startDate=new Date(start);if(!Number.isFinite(startDate.getTime()))throw new Error('موعد البداية غير صالح.');const end=$('#e-end').value;const endDate=end?new Date(end):null;if(endDate&&!Number.isFinite(endDate.getTime()))throw new Error('موعد النهاية غير صالح.');if(endDate&&endDate<=startDate)throw new Error('موعد النهاية يجب أن يكون بعد البداية.');const payload={titleAr:$('#e-title-ar').value,titleEn:$('#e-title-en').value,slug:$('#e-slug').value,type:$('#e-type').value,startsAt:startDate.toISOString(),endsAt:endDate?endDate.toISOString():'',location:$('#e-location').value,capacity:Number($('#e-capacity').value||0),price:Number($('#e-price').value||0),descriptionAr:$('#e-description').value,coverImageUrl:$('#e-image-url').value.trim(),videoUrl:'',status:$('#e-status').value,featured:$('#e-featured').checked,bookingEnabled:$('#e-booking').checked};let saved=editingId?await request('/api/experiences/'+editingId,{method:'PATCH',body:JSON.stringify(payload)}):await request('/api/experiences',{method:'POST',body:JSON.stringify(payload)});const file=$('#e-image-file').files[0];if(file){if(file.size>15*1024*1024)throw new Error('الحد الأقصى للصورة 15MB.');if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type))throw new Error('الصيغ المسموحة: JPG وPNG وWebP وAVIF.');const prepared=await request('/api/experiences/images/presign',{method:'POST',body:JSON.stringify({experienceId:saved.id,fileName:file.name,contentType:file.type,size:file.size})});const upload=await fetch(prepared.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!upload.ok)throw new Error('فشل رفع صورة الفعالية.');saved=await request('/api/experiences/'+saved.id,{method:'PATCH',body:JSON.stringify({coverImageKey:prepared.key,coverImageUrl:''})})}const videoFile=$('#e-video-file').files[0];if(videoFile){if(videoFile.size>MAX_VIDEO_BYTES)throw new Error('الحد الأقصى لفيديو الفعالية 120MB.');if(!VIDEO_TYPES.includes(videoFile.type))throw new Error('الصيغ المسموحة: MP4 وWebM وMOV.');const key=await uploadVideo(saved.id,videoFile);saved=await request('/api/experiences/'+saved.id,{method:'PATCH',body:JSON.stringify({videoKey:key,videoUrl:''})})}closeModal();await load()}catch(error){alert(error.message)}finally{button.disabled=false}});
load();
