const $=(selector)=>document.querySelector(selector);
const apiBase=()=>((localStorage.getItem('ARABISK_API_BASE')||window.ARABISK_API_BASE||import.meta.env.VITE_API_BASE_URL||(import.meta.env.DEV?'http://localhost:3000':'/proxy')).replace(/\/$/,''));
const columns=[{key:'new',statuses:['pending','confirmed'],label:'طلبات جديدة',empty:'لا توجد طلبات جديدة.',next:{pending:'confirmed',confirmed:'preparing'}} ,{key:'preparing',statuses:['preparing'],label:'قيد التحضير',empty:'لا توجد طلبات قيد التحضير.',next:{preparing:'ready'}},{key:'ready',statuses:['ready'],label:'جاهز',empty:'لا توجد طلبات جاهزة.',next:{ready:'completed'}}];
const actionLabels={pending:'تأكيد الطلب',confirmed:'بدء التحضير',preparing:'تم التحضير',ready:'إغلاق الطلب'};
let orders=[];let timer=null;
const esc=(v)=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
async function request(path,options={}){const r=await fetch(`${apiBase()}${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'تعذر الاتصال بالخادم');return data;}
function render(){const active=orders.filter(o=>o.status==='pending'||o.status==='confirmed'||o.status==='preparing'||o.status==='ready');$('#kitchen-count').textContent=active.length;$('#kitchen-state').textContent=active.length?`آخر تحديث ${new Date().toLocaleTimeString('ar-AE',{hour:'2-digit',minute:'2-digit'})}`:'لا توجد طلبات قيد التنفيذ.';for(const column of columns){const target=$(`#kitchen-${column.key}`);const list=orders.filter(o=>column.statuses.includes(o.status));target.innerHTML=list.map(order=>{const table=order.orderType==='dine_in'?(order.tableNumber?`طاولة ${esc(order.tableNumber)}`:'داخل المطعم'):'استلام';const items=(order.items||[]).map(i=>`<li><b>${Number(i.quantity)}×</b> ${esc(i.nameAr)}</li>`).join('');const next=column.next[order.status];return `<article class="k-card"><header><div><strong>${esc(order.id)}</strong><span>${table}</span></div><time>${new Date(order.createdAt).toLocaleTimeString('ar-AE',{hour:'2-digit',minute:'2-digit'})}</time></header><ul>${items||'<li>لا توجد أصناف</li>'}</ul>${order.notes?`<p class="k-notes">${esc(order.notes)}</p>`:''}<button class="k-next" data-id="${esc(order.id)}" data-next="${next}">${actionLabels[order.status]}</button></article>`}).join('')||`<div class="k-empty">${column.empty}</div>`;}}
async function load(){try{orders=await request('/api/orders');render();$('#kitchen-error').textContent='';}catch(e){$('#kitchen-error').textContent=e.message}}
$('#kitchen-refresh').addEventListener('click',load);document.addEventListener('click',async e=>{const btn=e.target.closest('[data-next]');if(!btn)return;btn.disabled=true;try{await request(`/api/orders/${btn.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:btn.dataset.next})});await load()}catch(err){alert(err.message);btn.disabled=false}});timer=setInterval(load,15000);window.addEventListener('beforeunload',()=>clearInterval(timer));load();
