const $=(selector)=>document.querySelector(selector);
const apiBase=()=>((localStorage.getItem('ARABISK_API_BASE')||window.ARABISK_API_BASE||import.meta.env.VITE_API_BASE_URL||(import.meta.env.DEV?'http://localhost:3000':'/proxy')).replace(/\/$/,''));
const statuses=['confirmed','preparing','ready'];
const labels={confirmed:'مؤكد',preparing:'قيد التحضير',ready:'جاهز'};
let orders=[];let timer=null;
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function request(path,options={}){const r=await fetch(`${apiBase()}${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'تعذر الاتصال بالخادم');return data;}
function render(){const active=orders.filter(o=>statuses.includes(o.status));$('#kitchen-count').textContent=active.length;$('#kitchen-state').textContent=active.length?`آخر تحديث ${new Date().toLocaleTimeString('ar-AE',{hour:'2-digit',minute:'2-digit'})}`:'لا توجد طلبات قيد التنفيذ.';const groups=Object.fromEntries(statuses.map(s=>[s,orders.filter(o=>o.status===s)]));for(const status of statuses){const target=$(`#kitchen-${status}`);target.innerHTML=groups[status].map(order=>{const table=order.orderType==='dine_in'?(order.tableNumber?`طاولة ${esc(order.tableNumber)}`:'داخل المطعم'):'استلام';const items=(order.items||[]).map(i=>`<li><b>${Number(i.quantity)}×</b> ${esc(i.nameAr)}</li>`).join('');return `<article class="k-card"><header><div><strong>${esc(order.id)}</strong><span>${table}</span></div><time>${new Date(order.createdAt).toLocaleTimeString('ar-AE',{hour:'2-digit',minute:'2-digit'})}</time></header><ul>${items||'<li>لا توجد أصناف</li>'}</ul>${order.notes?`<p class="k-notes">${esc(order.notes)}</p>`:''}<button class="k-next" data-id="${esc(order.id)}" data-next="${status==='confirmed'?'preparing':'ready'}">${status==='confirmed'?'بدء التحضير':status==='preparing'?'تم التحضير':'إغلاق الطلب'}</button></article>`}).join('')||'<div class="k-empty">لا توجد طلبات هنا.</div>';}}
async function load(){try{orders=await request('/api/orders');render();$('#kitchen-error').textContent='';}catch(e){$('#kitchen-error').textContent=e.message}}
$('#kitchen-refresh').addEventListener('click',load);document.addEventListener('click',async e=>{const btn=e.target.closest('[data-next]');if(!btn)return;btn.disabled=true;try{await request(`/api/orders/${btn.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:btn.dataset.next})});await load()}catch(err){alert(err.message);btn.disabled=false}});timer=setInterval(load,15000);window.addEventListener('beforeunload',()=>clearInterval(timer));load();
