import { request } from './api-client.js';
const state={orders:[],reservations:[],filter:'active'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'AED '+Number(v||0).toLocaleString('en-AE',{maximumFractionDigits:0});
const labels={pending:'قيد المراجعة',confirmed:'مؤكد',preparing:'قيد التحضير',ready:'جاهز',completed:'مكتمل',cancelled:'ملغي'};
const active=['pending','confirmed','preparing','ready'];
function today(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const g=t=>p.find(x=>x.type===t)?.value;return g('year')+'-'+g('month')+'-'+g('day');}
function age(iso){const t=new Date(iso||0).getTime();if(!Number.isFinite(t))return '';const m=Math.max(0,Math.round((Date.now()-t)/60000));return m<1?'منذ لحظات':m<60?'منذ '+m+' دقيقة':'منذ '+Math.floor(m/60)+' ساعة';}
function renderOrders(){const c={pending:0,preparing:0,ready:0};state.orders.forEach(o=>{if(c[o.status]!=null)c[o.status]++});const a=state.orders.filter(o=>active.includes(o.status));document.querySelector('#orders-ops-active-count').textContent=a.length;document.querySelector('#orders-ops-pending-count').textContent=c.pending||0;document.querySelector('#orders-ops-preparing-count').textContent=c.preparing||0;document.querySelector('#orders-ops-ready-count').textContent=c.ready||0;document.querySelector('#orders-ops-all-count').textContent=state.orders.length;let list=state.orders.slice();if(state.filter==='active')list=list.filter(o=>active.includes(o.status));else if(state.filter!=='all')list=list.filter(o=>o.status===state.filter);list.sort((x,y)=>new Date(y.createdAt||0)-new Date(x.createdAt||0));const body=document.querySelector('#orders-ops-list');body.innerHTML=list.slice(0,12).map(o=>{const items=(o.items||[]).slice(0,4).map(i=>esc(i.nameAr||i.name||'صنف')+' × '+Number(i.quantity||0)).join('، ')||'لا توجد تفاصيل أصناف';const priority=active.includes(o.status)&&((Date.now()-new Date(o.createdAt||0).getTime())/60000)>=20;return '<article class="ops-order-card '+(priority?'priority':'')+'"><div class="ops-order-head"><div><strong class="ops-order-id">#'+esc(o.id)+'</strong><span class="ops-order-time">'+esc(new Date(o.createdAt||0).toLocaleTimeString('ar-AE',{hour:'2-digit',minute:'2-digit'}))+'</span></div><strong class="ops-order-total">'+money(o.total)+'</strong></div><div class="ops-order-client"><strong>'+esc(o.name||'عميل')+'</strong><span>'+esc(o.phone||'')+'</span></div><p class="ops-order-items">'+items+'</p><div class="ops-order-foot"><span class="ops-order-status">'+esc(labels[o.status]||o.status||'غير معروف')+'</span><span class="ops-order-age">'+esc(age(o.createdAt))+'</span><button class="ops-order-jump" type="button" data-ops-order="'+esc(o.id)+'">فتح</button></div></article>';}).join('')||'<div class="ops-order-empty">لا توجد طلبات ضمن الفلتر الحالي.</div>';}
function renderReservations(){const d=today();const list=state.reservations.filter(r=>String(r.date||'').slice(0,10)===d).sort((a,b)=>String(a.time||'').localeCompare(String(b.time||'')));document.querySelector('#reservations-ops-today').textContent=list.length;document.querySelector('#reservations-ops-guests').textContent=list.reduce((s,r)=>s+Number(r.guests||0),0);document.querySelector('#reservations-ops-confirmed').textContent=list.filter(r=>r.status==='confirmed').length;document.querySelector('#reservations-ops-pending').textContent=list.filter(r=>!['confirmed','cancelled'].includes(r.status)).length;const body=document.querySelector('#reservations-ops-list');body.innerHTML=list.slice(0,10).map(r=>'<article class="reservation-ops-item"><div class="reservation-ops-main"><strong>'+esc(r.name||'ضيف')+'</strong><span>'+esc(r.phone||'')+'</span></div><div class="reservation-ops-meta"><b>'+esc(r.time||'—')+'</b><span>'+Number(r.guests||0)+' ضيف</span><span>'+esc(labels[r.status]||r.status||'قيد المراجعة')+'</span></div><button class="reservation-ops-action" type="button" data-ops-reservation="'+esc(r.id)+'">فتح الحجز</button></article>').join('')||'<div class="reservation-ops-empty">لا توجد حجوزات اليوم.</div>';}
function jump(section,id){document.querySelector('[data-section="'+CSS.escape(section)+'"]')?.click();setTimeout(()=>{const row=section==='orders'?document.querySelector('select[data-order-status="'+CSS.escape(id)+'"]')?.closest('tr'):document.querySelector('[data-id="'+CSS.escape(id)+'"]')?.closest('tr');row?.classList.add('customer360-highlight-row');row?.scrollIntoView({behavior:'smooth',block:'center'});},120);}
async function load(){const a=document.querySelector('#orders-ops-sync'),b=document.querySelector('#reservations-ops-sync');try{const r=await Promise.all([request('/api/orders'),request('/api/reservations')]);state.orders=Array.isArray(r[0])?r[0]:[];state.reservations=Array.isArray(r[1])?r[1]:[];renderOrders();renderReservations();[a,b].forEach(x=>{if(x){x.textContent='متصل الآن';x.classList.add('live')}})}catch(e){[a,b].forEach(x=>{if(x)x.textContent='تعذر التحديث'})}}
document.querySelector('#orders-ops-refresh')?.addEventListener('click',()=>void load());document.querySelector('#reservations-ops-refresh')?.addEventListener('click',()=>void load());document.querySelectorAll('[data-ops-order-filter]').forEach(b=>b.addEventListener('click',()=>{state.filter=b.dataset.opsOrderFilter||'active';document.querySelectorAll('[data-ops-order-filter]').forEach(x=>x.classList.toggle('active',x===b));renderOrders();}));document.addEventListener('click',e=>{const o=e.target.closest('[data-ops-order]');if(o)jump('orders',o.dataset.opsOrder);const r=e.target.closest('[data-ops-reservation]');if(r)jump('reservations',r.dataset.opsReservation);});
void load();